/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package khanaBadosh.Gui;

import java.awt.Dimension;
import java.awt.Frame;
import java.awt.Image;
import java.awt.Toolkit;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.SwingUtilities;
import javax.swing.UIManager;
import khanaBadosh.Dao.Employees_personalDao;
import khanaBadosh.dbutil.dbutil;
import khanaBadosh.pojo.employees_personal;

/**
 *
 * @author HP
 */
public class AddEmpFrame extends javax.swing.JFrame {
    
private String empid ,name ,education ,diploma,permanent,local,vechile,license,adhar,voter,pan,blood;
private Date dob;
private long contact,emergncy ;
public static Frame fr;    
/**
     * Creates new form AddEmpFrame
     */
    public AddEmpFrame() {
        initComponents();
         try {
             Dimension d = Toolkit.getDefaultToolkit().getScreenSize();
         setBounds(0,0,d.width, d.height);
       this.setResizable(false);
    UIManager.setLookAndFeel("com.sun.java.swing.plaf.windows.WindowsLookAndFeel");
   SwingUtilities.updateComponentTreeUI(scbar);
  
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
            SwingUtilities.updateComponentTreeUI(jPanel2);
        } catch (Throwable ex) {
            java.util.logging.Logger.getLogger(ViewFuelFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        this.setLocationRelativeTo(null);
           Toolkit t = Toolkit.getDefaultToolkit();
        Image im = t.getImage(getClass().getResource("/IMAGES/title.jpg"));
        setIconImage(im);
  
        try{
        String EmpId = Employees_personalDao.generateId();
        txtEmpId.setText(EmpId);
        UIManager.setLookAndFeel("com.sun.java.swing.plaf.windows.WindowsLookAndFeel");
        SwingUtilities.updateComponentTreeUI(jScrollPane2);
        SwingUtilities.updateComponentTreeUI(jScrollPane1);

        }
        catch(Throwable th)
        {
            JOptionPane.showMessageDialog(null,"Contact MasterAdmin","ERROR",JOptionPane.ERROR_MESSAGE);
      
            th.printStackTrace();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        scbar = new javax.swing.JScrollPane();
        jPanel2 = new javax.swing.JPanel();
        txtdiploma = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        txtblood = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtlocal = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtpermanent = new javax.swing.JTextArea();
        txteducation = new javax.swing.JTextField();
        jLabel21 = new javax.swing.JLabel();
        txtpan = new javax.swing.JTextField();
        txtEmpId = new javax.swing.JTextField();
        txtname = new javax.swing.JTextField();
        jLabel22 = new javax.swing.JLabel();
        txtcontact = new javax.swing.JTextField();
        jLabel23 = new javax.swing.JLabel();
        txtemergency = new javax.swing.JTextField();
        jLabel24 = new javax.swing.JLabel();
        txtvechile = new javax.swing.JTextField();
        jLabel25 = new javax.swing.JLabel();
        txtlicense = new javax.swing.JTextField();
        jLabel26 = new javax.swing.JLabel();
        txtaadhaar = new javax.swing.JTextField();
        jLabel27 = new javax.swing.JLabel();
        txtvoter = new javax.swing.JTextField();
        jLabel29 = new javax.swing.JLabel();
        txtdate = new com.toedter.calendar.JDateChooser();
        btnSave = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 51, 0), 1, true), " ADD EMPLOYEES DETAILS", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Tahoma", 1, 24), new java.awt.Color(255, 102, 0))); // NOI18N
        jPanel2.setMinimumSize(new java.awt.Dimension(1240, 640));
        jPanel2.setPreferredSize(new java.awt.Dimension(1240, 670));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtdiploma.setFont(new java.awt.Font("Trebuchet MS", 0, 20)); // NOI18N
        txtdiploma.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel2.add(txtdiploma, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 140, 320, 30));

        jLabel12.setFont(new java.awt.Font("Trebuchet MS", 2, 20)); // NOI18N
        jLabel12.setText("Employee Id           :");
        jPanel2.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, 220, -1));

        txtblood.setFont(new java.awt.Font("Trebuchet MS", 0, 20)); // NOI18N
        txtblood.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel2.add(txtblood, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 510, 300, 30));

        jLabel13.setFont(new java.awt.Font("Trebuchet MS", 2, 20)); // NOI18N
        jLabel13.setText("Employee Name*       :");
        jPanel2.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 30, 230, -1));

        jLabel14.setFont(new java.awt.Font("Trebuchet MS", 2, 20)); // NOI18N
        jLabel14.setText("Emergency Contact No.* :");
        jPanel2.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 340, 260, -1));

        jLabel16.setFont(new java.awt.Font("Trebuchet MS", 2, 20)); // NOI18N
        jLabel16.setText("(Highest Qualification)");
        jPanel2.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 170, 230, -1));

        jLabel17.setFont(new java.awt.Font("Trebuchet MS", 2, 20)); // NOI18N
        jLabel17.setText("Permanent Address*   :");
        jPanel2.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 210, 240, -1));

        jLabel18.setFont(new java.awt.Font("Trebuchet MS", 2, 20)); // NOI18N
        jLabel18.setText("Local  Address*         :");
        jPanel2.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 200, 240, -1));

        jLabel19.setFont(new java.awt.Font("Trebuchet MS", 2, 20)); // NOI18N
        jLabel19.setText("Date of Birth*          :");
        jPanel2.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, 220, -1));

        jLabel20.setFont(new java.awt.Font("Trebuchet MS", 2, 20)); // NOI18N
        jLabel20.setText("Education Qualification* :");
        jPanel2.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 140, 260, -1));

        txtlocal.setColumns(5);
        txtlocal.setFont(new java.awt.Font("Trebuchet MS", 0, 20)); // NOI18N
        txtlocal.setLineWrap(true);
        txtlocal.setRows(3);
        txtlocal.setWrapStyleWord(true);
        jScrollPane1.setViewportView(txtlocal);

        jPanel2.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 200, 320, 110));

        txtpermanent.setColumns(4);
        txtpermanent.setFont(new java.awt.Font("Trebuchet MS", 0, 20)); // NOI18N
        txtpermanent.setLineWrap(true);
        txtpermanent.setRows(3);
        txtpermanent.setTabSize(4);
        txtpermanent.setWrapStyleWord(true);
        jScrollPane2.setViewportView(txtpermanent);

        jPanel2.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 200, 280, 110));

        txteducation.setFont(new java.awt.Font("Trebuchet MS", 0, 20)); // NOI18N
        txteducation.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel2.add(txteducation, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 140, 260, 30));

        jLabel21.setFont(new java.awt.Font("Trebuchet MS", 2, 20)); // NOI18N
        jLabel21.setText("License No             :  ");
        jPanel2.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 400, 230, -1));

        txtpan.setFont(new java.awt.Font("Trebuchet MS", 0, 20)); // NOI18N
        txtpan.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel2.add(txtpan, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 510, 280, 30));

        txtEmpId.setEditable(false);
        txtEmpId.setBackground(new java.awt.Color(255, 255, 255));
        txtEmpId.setFont(new java.awt.Font("Trebuchet MS", 0, 20)); // NOI18N
        txtEmpId.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel2.add(txtEmpId, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 30, 280, 30));

        txtname.setFont(new java.awt.Font("Trebuchet MS", 0, 20)); // NOI18N
        txtname.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel2.add(txtname, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 30, 320, 30));

        jLabel22.setFont(new java.awt.Font("Trebuchet MS", 2, 20)); // NOI18N
        jLabel22.setText("Contact No.*          :");
        jPanel2.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 340, 220, -1));

        txtcontact.setFont(new java.awt.Font("Trebuchet MS", 0, 20)); // NOI18N
        txtcontact.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel2.add(txtcontact, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 340, 280, 30));

        jLabel23.setFont(new java.awt.Font("Trebuchet MS", 2, 20)); // NOI18N
        jLabel23.setText("Blood Group*          :");
        jPanel2.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 510, 220, -1));

        txtemergency.setFont(new java.awt.Font("Trebuchet MS", 0, 20)); // NOI18N
        txtemergency.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel2.add(txtemergency, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 340, 300, 30));

        jLabel24.setFont(new java.awt.Font("Trebuchet MS", 2, 20)); // NOI18N
        jLabel24.setText("Vechile No.           :");
        jPanel2.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 400, 210, -1));

        txtvechile.setFont(new java.awt.Font("Trebuchet MS", 0, 20)); // NOI18N
        txtvechile.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel2.add(txtvechile, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 400, 280, 30));

        jLabel25.setFont(new java.awt.Font("Trebuchet MS", 2, 20)); // NOI18N
        jLabel25.setText("PanCard No.          :");
        jPanel2.add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 510, 210, -1));

        txtlicense.setFont(new java.awt.Font("Trebuchet MS", 0, 20)); // NOI18N
        txtlicense.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel2.add(txtlicense, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 400, 300, 30));

        jLabel26.setFont(new java.awt.Font("Trebuchet MS", 2, 20)); // NOI18N
        jLabel26.setText("AadhaarCard No.*   :");
        jPanel2.add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 460, 210, -1));

        txtaadhaar.setFont(new java.awt.Font("Trebuchet MS", 0, 20)); // NOI18N
        txtaadhaar.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel2.add(txtaadhaar, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 460, 280, 30));

        jLabel27.setFont(new java.awt.Font("Trebuchet MS", 2, 20)); // NOI18N
        jLabel27.setText("Voter Id No.           :");
        jPanel2.add(jLabel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 460, 220, -1));

        txtvoter.setFont(new java.awt.Font("Trebuchet MS", 0, 20)); // NOI18N
        txtvoter.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel2.add(txtvoter, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 460, 300, 30));

        jLabel29.setFont(new java.awt.Font("Trebuchet MS", 2, 20)); // NOI18N
        jLabel29.setText("Diploma Course         :");
        jPanel2.add(jLabel29, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 140, 230, -1));

        txtdate.setBackground(new java.awt.Color(255, 255, 255));
        txtdate.setForeground(new java.awt.Color(255, 0, 51));
        txtdate.setDateFormatString("dd MMM,yyy");
        txtdate.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jPanel2.add(txtdate, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 90, 280, 30));

        btnSave.setBackground(new java.awt.Color(255, 102, 0));
        btnSave.setFont(new java.awt.Font("Tahoma", 3, 20)); // NOI18N
        btnSave.setForeground(new java.awt.Color(255, 255, 255));
        btnSave.setText("Save And Next");
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });
        jPanel2.add(btnSave, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 607, 230, -1));

        jButton4.setBackground(new java.awt.Color(255, 102, 0));
        jButton4.setFont(new java.awt.Font("Tahoma", 3, 20)); // NOI18N
        jButton4.setForeground(new java.awt.Color(255, 255, 255));
        jButton4.setText("QUIT");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 607, 120, -1));

        jButton3.setBackground(new java.awt.Color(255, 102, 0));
        jButton3.setFont(new java.awt.Font("Tahoma", 3, 20)); // NOI18N
        jButton3.setForeground(new java.awt.Color(255, 255, 255));
        jButton3.setText("BACK");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 607, 120, -1));

        jButton2.setBackground(new java.awt.Color(255, 102, 0));
        jButton2.setFont(new java.awt.Font("Tahoma", 3, 20)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("CLEAR");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 607, 130, -1));

        scbar.setViewportView(jPanel2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(scbar, javax.swing.GroupLayout.DEFAULT_SIZE, 1198, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(scbar, javax.swing.GroupLayout.DEFAULT_SIZE, 668, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
if(validat())
{
try
{
    name = txtname.getText();
    education = txteducation.getText();
    diploma = txtdiploma.getText()+"";
    permanent = txtpermanent.getText();
    local = txtlocal.getText();
    vechile = txtvechile.getText()+"";
    license = txtlicense.getText()+"";
    adhar = txtaadhaar.getText();
    pan = txtpan.getText()+"";
    voter = txtvoter.getText()+"";
    blood = txtblood.getText();
    dob = txtdate.getDate();
    empid = txtEmpId.getText();
    employees_personal emp_p = new employees_personal();
    emp_p.setName(name);
    emp_p.setDob(dob);
    emp_p.setAdhar(adhar);
    emp_p.setBlood(blood);
    emp_p.setContact(contact);
    emp_p.setEducation(education);
    emp_p.setEmergncy(emergncy);
    emp_p.setLicense(license);
    emp_p.setLocal(local);
    emp_p.setPan(pan);
    emp_p.setPermanent(permanent);
    emp_p.setVechile(vechile);
    emp_p.setVoter(voter);
    emp_p.setDiploma(diploma);
    emp_p.setEmpid(empid);
    
    this.setVisible(false);
       fr = this ;
       if(AddEmpJobFrame.fr1==null)
      new AddEmpJobFrame(emp_p).setVisible(true);
        else
           AddEmpJobFrame.fr1.setVisible(true);
  
}
catch(Throwable th)
{
     JOptionPane.showMessageDialog(null,"Adding Personal details is Unsuccessfull."+th.getMessage(),"Error",JOptionPane.ERROR_MESSAGE);
 
    th.printStackTrace();
}


}     




        // TODO add your handling code here:
    }//GEN-LAST:event_btnSaveActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
this.dispose();
new AdminOptionFrame().setVisible(true);
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
dbutil.closeConnection();
        System.exit(0);
// TODO add your handling code here:
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
this.dispose();
new AddEmpFrame().setVisible(true);// TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AddEmpFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AddEmpFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AddEmpFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AddEmpFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AddEmpFrame().setVisible(true);
            }
        });


    }

    @Override
    public int getDefaultCloseOperation() {
        dbutil.closeConnection();
        return super.getDefaultCloseOperation(); //To change body of generated methods, choose Tools | Templates.
    }
    
    private boolean validat()
    {
        if(txtname.getText().isEmpty()||txteducation.getText().isEmpty()||txtpermanent.getText().isEmpty()||txtlocal.getText().isEmpty()||txtcontact.getText().isEmpty()||txtemergency.getText().isEmpty()||txtblood.getText().isEmpty())
        {
       JOptionPane.showMessageDialog(null, "Please Fill All the Mandatory(*) Fields", "EMPTY FIELDS(*)", JOptionPane.ERROR_MESSAGE);
            return false;
        }
        else
        {
            try
       {
           contact = Long.parseLong(txtcontact.getText());
           emergncy = Long.parseLong(txtemergency.getText());
           if(contact == emergncy)
           {
    JOptionPane.showMessageDialog(null, "Emergency no. and contact no. should be Different", "ERROR Contact/Emergency", JOptionPane.ERROR_MESSAGE);
      return false;
           }
       }
       catch(NumberFormatException neq)
       {
         JOptionPane.showMessageDialog(null, "Please write a valid emergency no. and contact no.", "Invalid Contact/Emergency", JOptionPane.ERROR_MESSAGE);
       return false;
       }
       
            return true;
        }
            }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSave;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane scbar;
    private javax.swing.JTextField txtEmpId;
    private javax.swing.JTextField txtaadhaar;
    private javax.swing.JTextField txtblood;
    private javax.swing.JTextField txtcontact;
    private com.toedter.calendar.JDateChooser txtdate;
    private javax.swing.JTextField txtdiploma;
    private javax.swing.JTextField txteducation;
    private javax.swing.JTextField txtemergency;
    private javax.swing.JTextField txtlicense;
    private javax.swing.JTextArea txtlocal;
    private javax.swing.JTextField txtname;
    private javax.swing.JTextField txtpan;
    private javax.swing.JTextArea txtpermanent;
    private javax.swing.JTextField txtvechile;
    private javax.swing.JTextField txtvoter;
    // End of variables declaration//GEN-END:variables
}
