/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package khanaBadosh.Gui;

import java.awt.Dimension;
import java.awt.Frame;
import java.awt.Image;
import java.awt.Toolkit;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.SwingUtilities;
import javax.swing.UIManager;
import khanaBadosh.dbutil.dbutil;
import khanaBadosh.pojo.UserProfile;

/**
 *
 * @author HP
 */
public class AdminOptionFrame extends javax.swing.JFrame {

    /**
     * Creates new form AdminOptionFrame
     */
    public AdminOptionFrame() {
        initComponents();
         try {
             Dimension d = Toolkit.getDefaultToolkit().getScreenSize();
         setBounds(0,0,d.width, d.height);
       this.setResizable(false);
   UIManager.setLookAndFeel("com.sun.java.swing.plaf.windows.WindowsLookAndFeel");
   SwingUtilities.updateComponentTreeUI(scbar);
  
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
             SwingUtilities.updateComponentTreeUI(jPanel1);
        } catch (Throwable ex) {
            java.util.logging.Logger.getLogger(ViewFuelFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        this.setLocationRelativeTo(null);
         Toolkit t = Toolkit.getDefaultToolkit();
        Image im = t.getImage(getClass().getResource("/IMAGES/title.jpg"));
        setIconImage(im);
  
Image img = t.getImage(getClass().getResource("/IMAGES/SIDE3.jpg")).getScaledInstance(jLabel5.getWidth(),jLabel5.getHeight(),Image.SCALE_SMOOTH);
ImageIcon icon=new ImageIcon(img);
jLabel5.setIcon(icon);
 img = t.getImage(getClass().getResource("/IMAGES/SIDE.jpg")).getScaledInstance(jLabel6.getWidth(),jLabel6.getHeight(),Image.SCALE_SMOOTH);
 icon=new ImageIcon(img);
jLabel6.setIcon(icon);
 img = t.getImage(getClass().getResource("/IMAGES/Untitled-1-copy.jpg")).getScaledInstance(jLabel8.getWidth(),jLabel8.getHeight(),Image.SCALE_SMOOTH);
 icon=new ImageIcon(img);
jLabel8.setIcon(icon);


        if(UserProfile.getUsertype().equalsIgnoreCase("MASTER ADMIN"))
            panelMA.setVisible(true);
        else
            panelMA.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        scbar = new javax.swing.JScrollPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        panelMA = new javax.swing.JPanel();
        btnAddAdmin = new javax.swing.JRadioButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        btnDoTask = new javax.swing.JButton();
        btnQuit = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        btnAddEmp = new javax.swing.JRadioButton();
        jPanel9 = new javax.swing.JPanel();
        btnpersonal = new javax.swing.JRadioButton();
        btnjob = new javax.swing.JRadioButton();
        jPanel8 = new javax.swing.JPanel();
        btnEditFuel = new javax.swing.JRadioButton();
        jPanel10 = new javax.swing.JPanel();
        btnAddEmpWise = new javax.swing.JRadioButton();
        btnallentries = new javax.swing.JRadioButton();
        btnAddFuel = new javax.swing.JRadioButton();
        btnBack = new javax.swing.JButton();
        jPanel6 = new javax.swing.JPanel();
        btngenerateinvoice = new javax.swing.JRadioButton();
        jPanel11 = new javax.swing.JPanel();
        btnAddEmpWise1 = new javax.swing.JRadioButton();
        btnallentries1 = new javax.swing.JRadioButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGES/SIDE.jpg"))); // NOI18N
        jLabel6.setText("jLabel5");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(960, 0, 280, 210));

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGES/Untitled-1-copy.jpg"))); // NOI18N
        jLabel8.setText("jLabel8");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 960, 160));

        panelMA.setBackground(new java.awt.Color(255, 255, 255));
        panelMA.setBorder(javax.swing.BorderFactory.createTitledBorder(null, " MASTER ADMIN ", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.ABOVE_TOP, new java.awt.Font("Tahoma", 1, 24), new java.awt.Color(255, 153, 0))); // NOI18N
        panelMA.setForeground(new java.awt.Color(255, 0, 0));
        panelMA.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnAddAdmin.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroup1.add(btnAddAdmin);
        btnAddAdmin.setFont(new java.awt.Font("Tahoma", 3, 20)); // NOI18N
        btnAddAdmin.setForeground(new java.awt.Color(255, 0, 0));
        btnAddAdmin.setText("ADD ADMIN");
        btnAddAdmin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddAdminActionPerformed(evt);
            }
        });
        panelMA.add(btnAddAdmin, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, 160, -1));

        jPanel1.add(panelMA, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 230, 220, 160));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGES/SIDE3.jpg"))); // NOI18N
        jLabel5.setText("jLabel5");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 370, 220, 320));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGES/SIDE2.jpg"))); // NOI18N
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 640, 1020, 50));

        btnDoTask.setBackground(new java.awt.Color(255, 102, 0));
        btnDoTask.setFont(new java.awt.Font("Tahoma", 3, 20)); // NOI18N
        btnDoTask.setForeground(new java.awt.Color(255, 255, 255));
        btnDoTask.setText("Do Task");
        btnDoTask.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDoTaskActionPerformed(evt);
            }
        });
        jPanel1.add(btnDoTask, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 600, 150, 30));

        btnQuit.setBackground(new java.awt.Color(255, 102, 0));
        btnQuit.setFont(new java.awt.Font("Tahoma", 3, 20)); // NOI18N
        btnQuit.setForeground(new java.awt.Color(255, 255, 255));
        btnQuit.setText("QUIT");
        btnQuit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnQuitActionPerformed(evt);
            }
        });
        jPanel1.add(btnQuit, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 600, 150, 30));

        jLabel1.setFont(new java.awt.Font("Tahoma", 3, 24)); // NOI18N
        jLabel1.setText("BADOSH");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 190, 110, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 3, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 51, 0));
        jLabel2.setText("KHANA                  ADMIN PANEL");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 190, 540, -1));

        jPanel7.setBackground(new java.awt.Color(255, 255, 255));
        jPanel7.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "EMPLOYEE OPTIONS", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.ABOVE_TOP, new java.awt.Font("Tahoma", 1, 24), new java.awt.Color(255, 153, 0))); // NOI18N
        jPanel7.setForeground(new java.awt.Color(255, 0, 0));
        jPanel7.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnAddEmp.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroup1.add(btnAddEmp);
        btnAddEmp.setFont(new java.awt.Font("Tahoma", 3, 20)); // NOI18N
        btnAddEmp.setForeground(new java.awt.Color(255, 0, 0));
        btnAddEmp.setText("ADD EMPLOYEE");
        btnAddEmp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddEmpActionPerformed(evt);
            }
        });
        jPanel7.add(btnAddEmp, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 60, 220, -1));

        jPanel9.setBackground(new java.awt.Color(255, 255, 255));
        jPanel9.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "View Option", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.ABOVE_TOP, new java.awt.Font("Tahoma", 1, 24), new java.awt.Color(255, 153, 0))); // NOI18N
        jPanel9.setForeground(new java.awt.Color(255, 0, 0));
        jPanel9.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnpersonal.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroup1.add(btnpersonal);
        btnpersonal.setFont(new java.awt.Font("Tahoma", 3, 20)); // NOI18N
        btnpersonal.setForeground(new java.awt.Color(255, 0, 0));
        btnpersonal.setText("Personal Details");
        btnpersonal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnpersonalActionPerformed(evt);
            }
        });
        jPanel9.add(btnpersonal, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, 230, -1));

        btnjob.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroup1.add(btnjob);
        btnjob.setFont(new java.awt.Font("Tahoma", 3, 20)); // NOI18N
        btnjob.setForeground(new java.awt.Color(255, 0, 0));
        btnjob.setText("Job Details");
        jPanel9.add(btnjob, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 110, 180, -1));

        jPanel7.add(jPanel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 120, 250, 180));

        jPanel1.add(jPanel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 230, 270, 310));

        jPanel8.setBackground(new java.awt.Color(255, 255, 255));
        jPanel8.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "FUEL ENTRY OPTIONS", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.ABOVE_TOP, new java.awt.Font("Tahoma", 1, 24), new java.awt.Color(255, 153, 0))); // NOI18N
        jPanel8.setForeground(new java.awt.Color(255, 0, 0));
        jPanel8.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnEditFuel.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroup1.add(btnEditFuel);
        btnEditFuel.setFont(new java.awt.Font("Tahoma", 3, 20)); // NOI18N
        btnEditFuel.setForeground(new java.awt.Color(255, 0, 0));
        btnEditFuel.setText("EDIT FUEL ENTRY");
        btnEditFuel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditFuelActionPerformed(evt);
            }
        });
        jPanel8.add(btnEditFuel, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 120, 260, -1));

        jPanel10.setBackground(new java.awt.Color(255, 255, 255));
        jPanel10.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "View Options", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.ABOVE_TOP, new java.awt.Font("Tahoma", 1, 24), new java.awt.Color(255, 153, 0))); // NOI18N
        jPanel10.setForeground(new java.awt.Color(255, 0, 0));
        jPanel10.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnAddEmpWise.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroup1.add(btnAddEmpWise);
        btnAddEmpWise.setFont(new java.awt.Font("Tahoma", 3, 20)); // NOI18N
        btnAddEmpWise.setForeground(new java.awt.Color(255, 0, 0));
        btnAddEmpWise.setText("EMP WISE ENTRY");
        btnAddEmpWise.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddEmpWiseActionPerformed(evt);
            }
        });
        jPanel10.add(btnAddEmpWise, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 110, 240, -1));

        btnallentries.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroup1.add(btnallentries);
        btnallentries.setFont(new java.awt.Font("Tahoma", 3, 20)); // NOI18N
        btnallentries.setForeground(new java.awt.Color(255, 0, 0));
        btnallentries.setText("ALL ENTRIES");
        btnallentries.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnallentriesActionPerformed(evt);
            }
        });
        jPanel10.add(btnallentries, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, 230, -1));

        jPanel8.add(jPanel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 170, 270, 180));

        btnAddFuel.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroup1.add(btnAddFuel);
        btnAddFuel.setFont(new java.awt.Font("Tahoma", 3, 20)); // NOI18N
        btnAddFuel.setForeground(new java.awt.Color(255, 0, 0));
        btnAddFuel.setText("ENTER FUEL");
        btnAddFuel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddFuelActionPerformed(evt);
            }
        });
        jPanel8.add(btnAddFuel, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, 190, -1));

        jPanel1.add(jPanel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 230, 290, 360));

        btnBack.setBackground(new java.awt.Color(255, 102, 0));
        btnBack.setFont(new java.awt.Font("Tahoma", 3, 20)); // NOI18N
        btnBack.setForeground(new java.awt.Color(255, 255, 255));
        btnBack.setText("BACK");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });
        jPanel1.add(btnBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 600, 150, 30));

        jPanel6.setBackground(new java.awt.Color(255, 255, 255));
        jPanel6.setBorder(javax.swing.BorderFactory.createTitledBorder(null, " INVOICE OPTIONS ", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.ABOVE_TOP, new java.awt.Font("Tahoma", 1, 24), new java.awt.Color(255, 153, 0))); // NOI18N
        jPanel6.setForeground(new java.awt.Color(255, 0, 0));
        jPanel6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btngenerateinvoice.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroup1.add(btngenerateinvoice);
        btngenerateinvoice.setFont(new java.awt.Font("Tahoma", 3, 20)); // NOI18N
        btngenerateinvoice.setForeground(new java.awt.Color(255, 0, 0));
        btngenerateinvoice.setText("GENERATE INVOICE");
        btngenerateinvoice.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btngenerateinvoiceActionPerformed(evt);
            }
        });
        jPanel6.add(btngenerateinvoice, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, 280, -1));

        jPanel11.setBackground(new java.awt.Color(255, 255, 255));
        jPanel11.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "View Options", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.ABOVE_TOP, new java.awt.Font("Tahoma", 1, 24), new java.awt.Color(255, 153, 0))); // NOI18N
        jPanel11.setForeground(new java.awt.Color(255, 0, 0));
        jPanel11.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnAddEmpWise1.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroup1.add(btnAddEmpWise1);
        btnAddEmpWise1.setFont(new java.awt.Font("Tahoma", 3, 20)); // NOI18N
        btnAddEmpWise1.setForeground(new java.awt.Color(255, 0, 0));
        btnAddEmpWise1.setText("EMP WISE ENTRY");
        btnAddEmpWise1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddEmpWise1ActionPerformed(evt);
            }
        });
        jPanel11.add(btnAddEmpWise1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 110, 240, -1));

        btnallentries1.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroup1.add(btnallentries1);
        btnallentries1.setFont(new java.awt.Font("Tahoma", 3, 20)); // NOI18N
        btnallentries1.setForeground(new java.awt.Color(255, 0, 0));
        btnallentries1.setText("ALL ENTRIES");
        btnallentries1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnallentries1ActionPerformed(evt);
            }
        });
        jPanel11.add(btnallentries1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, 230, -1));

        jPanel6.add(jPanel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 160, 280, 180));

        jPanel1.add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 230, 300, 350));

        scbar.setViewportView(jPanel1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(scbar, javax.swing.GroupLayout.DEFAULT_SIZE, 1198, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(scbar, javax.swing.GroupLayout.DEFAULT_SIZE, 690, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btngenerateinvoiceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btngenerateinvoiceActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btngenerateinvoiceActionPerformed

    private void btnAddEmpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddEmpActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnAddEmpActionPerformed

    private void btnEditFuelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditFuelActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnEditFuelActionPerformed

    private void btnAddAdminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddAdminActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnAddAdminActionPerformed

    private void btnDoTaskActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDoTaskActionPerformed
Frame fr=null;
if(btnAddEmp.isSelected())
    fr=new AddEmpFrame();
else if(btnAddFuel.isSelected())
    fr = new FuelFrame();
else if(btnEditFuel.isSelected())
    fr = new FuelEditingFrame();
else if(btnpersonal.isSelected())
    fr = new ViewEmpFrame();
else if(btnjob.isSelected())
    fr= new ViewEmpJobFrame();
else if(btnallentries.isSelected())
    fr = new ViewFuelFrame();
else if(btnAddAdmin.isSelected())
    fr = new AddAdminFrame();
else if(btnAddEmpWise.isSelected())
    fr = new EmpWiseFrame();
else if(btngenerateinvoice.isSelected())
    fr = new GenerateInvoice();





if(fr!=null){
    fr.setVisible(true);
    this.dispose();
}
else
    JOptionPane.showMessageDialog(null,"Please select Some Option","NOT Selected",JOptionPane.INFORMATION_MESSAGE);


        // TODO add your handling code here:
    }//GEN-LAST:event_btnDoTaskActionPerformed

    private void btnpersonalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnpersonalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnpersonalActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
this.dispose();
new LoginFrame().setVisible(true);// TODO add your handling code here:
    }//GEN-LAST:event_btnBackActionPerformed

    private void btnQuitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnQuitActionPerformed
int ans;
        ans=JOptionPane.showConfirmDialog(null, "Are u sure ?","Quitting!",JOptionPane.YES_NO_OPTION,JOptionPane.QUESTION_MESSAGE);
        if(ans==JOptionPane.YES_OPTION)
        {
            dbutil.closeConnection();
            System.exit(0);
     
        }   
// TODO add your handling code here:
    }//GEN-LAST:event_btnQuitActionPerformed

    private void btnAddEmpWiseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddEmpWiseActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnAddEmpWiseActionPerformed

    private void btnallentriesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnallentriesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnallentriesActionPerformed

    private void btnAddFuelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddFuelActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnAddFuelActionPerformed

    private void btnAddEmpWise1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddEmpWise1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnAddEmpWise1ActionPerformed

    private void btnallentries1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnallentries1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnallentries1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdminOptionFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdminOptionFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdminOptionFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdminOptionFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AdminOptionFrame().setVisible(true);
            }
        });
        
    }

    @Override
    public int getDefaultCloseOperation() {
        dbutil.closeConnection();
        return super.getDefaultCloseOperation(); //To change body of generated methods, choose Tools | Templates.
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton btnAddAdmin;
    private javax.swing.JRadioButton btnAddEmp;
    private javax.swing.JRadioButton btnAddEmpWise;
    private javax.swing.JRadioButton btnAddEmpWise1;
    private javax.swing.JRadioButton btnAddFuel;
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnDoTask;
    private javax.swing.JRadioButton btnEditFuel;
    private javax.swing.JButton btnQuit;
    private javax.swing.JRadioButton btnallentries;
    private javax.swing.JRadioButton btnallentries1;
    private javax.swing.JRadioButton btngenerateinvoice;
    private javax.swing.JRadioButton btnjob;
    private javax.swing.JRadioButton btnpersonal;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JPanel panelMA;
    private javax.swing.JScrollPane scbar;
    // End of variables declaration//GEN-END:variables
}
