/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package khanaBadosh.Gui;

import java.awt.Dimension;
import java.awt.Image;
import java.awt.Toolkit;
import java.util.ArrayList;
import java.util.Iterator;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.SwingUtilities;
import javax.swing.UIManager;
import javax.swing.table.DefaultTableModel;
import khanaBadosh.Dao.Employees_jobDao;
import khanaBadosh.Dao.fuelDao;
import java.sql.Date;
import khanaBadosh.dbutil.dbutil;
import khanaBadosh.pojo.fuel;

/**
 *
 * @author HP
 */
public class EmpWiseFrame extends javax.swing.JFrame  {
ArrayList<String> al ;
public static Date d1 , d2;
 DefaultTableModel model ;
   
 
    /**
     * Creates new form EmpWiseFrame
     */
    public EmpWiseFrame() {
        initComponents();
        Dimension d = Toolkit.getDefaultToolkit().getScreenSize();
         setBounds(0,0,d.width, d.height);
       this.setResizable(false);
  
         try {
              UIManager.setLookAndFeel("com.sun.java.swing.plaf.windows.WindowsLookAndFeel");
   SwingUtilities.updateComponentTreeUI(scbar);
  
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
             SwingUtilities.updateComponentTreeUI(jPanel1);
        } catch (Throwable ex) {
            java.util.logging.Logger.getLogger(ViewFuelFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
         Toolkit t = Toolkit.getDefaultToolkit();
        Image im = t.getImage(getClass().getResource("/IMAGES/title.jpg"));
        setIconImage(im);
  
Image img = t.getImage(getClass().getResource("/IMAGES/SIDE3.jpg")).getScaledInstance(jLabel5.getWidth(),jLabel5.getHeight(),Image.SCALE_SMOOTH);
ImageIcon icon=new ImageIcon(img);
jLabel5.setIcon(icon);
 
 img = t.getImage(getClass().getResource("/IMAGES/Untitled-1-copy.jpg")).getScaledInstance(jLabel8.getWidth(),jLabel8.getHeight(),Image.SCALE_SMOOTH);
 icon=new ImageIcon(img);
jLabel8.setIcon(icon);


        this.setLocationRelativeTo(null);
       
         try{
              UIManager.setLookAndFeel("com.sun.java.swing.plaf.windows.WindowsLookAndFeel");
    SwingUtilities.updateComponentTreeUI(jPanel7);
 
            al = Employees_jobDao.getEmpId();
            for(String x:al)
            {
             jcempid.addItem(x);
            }
        }
        catch(Throwable th)
        {
            th.printStackTrace();
        }
    
    }

  

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        scbar = new javax.swing.JScrollPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        btnQuit = new javax.swing.JButton();
        jcempid = new javax.swing.JComboBox<>();
        btnback = new javax.swing.JButton();
        btnshowrecords = new javax.swing.JButton();
        jPanel7 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        EmpList = new javax.swing.JTable();
        jCheckBox1 = new javax.swing.JCheckBox();
        txttotal = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGES/tenor (1).gif"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 160, 220, 180));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGES/SIDE3.jpg"))); // NOI18N
        jLabel5.setText("jLabel5");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 340, 240, 330));

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGES/Untitled-1-copy.jpg"))); // NOI18N
        jLabel8.setText("jLabel8");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 10, 1090, 140));

        btnQuit.setBackground(new java.awt.Color(204, 0, 0));
        btnQuit.setFont(new java.awt.Font("Tahoma", 3, 20)); // NOI18N
        btnQuit.setForeground(new java.awt.Color(255, 255, 255));
        btnQuit.setText("QUIT");
        btnQuit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnQuitActionPerformed(evt);
            }
        });
        jPanel1.add(btnQuit, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 610, 130, 30));

        jcempid.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jcempid.setOpaque(false);
        jcempid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcempidActionPerformed(evt);
            }
        });
        jPanel1.add(jcempid, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 170, 290, -1));

        btnback.setBackground(new java.awt.Color(204, 0, 0));
        btnback.setFont(new java.awt.Font("Tahoma", 3, 20)); // NOI18N
        btnback.setForeground(new java.awt.Color(255, 255, 255));
        btnback.setText("BACK");
        btnback.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnbackActionPerformed(evt);
            }
        });
        jPanel1.add(btnback, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 610, 130, 30));

        btnshowrecords.setBackground(new java.awt.Color(204, 0, 0));
        btnshowrecords.setFont(new java.awt.Font("Tahoma", 3, 20)); // NOI18N
        btnshowrecords.setForeground(new java.awt.Color(255, 255, 255));
        btnshowrecords.setText("Show Records");
        btnshowrecords.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnshowrecordsActionPerformed(evt);
            }
        });
        jPanel1.add(btnshowrecords, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 170, 220, 30));

        jPanel7.setBackground(new java.awt.Color(255, 255, 255));
        jPanel7.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "FUEL DEAILS :", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.ABOVE_TOP, new java.awt.Font("Tahoma", 1, 23), new java.awt.Color(255, 153, 0))); // NOI18N
        jPanel7.setForeground(new java.awt.Color(255, 0, 0));
        jPanel7.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        EmpList.setBackground(new java.awt.Color(224, 0, 0));
        EmpList.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        EmpList.setForeground(new java.awt.Color(255, 255, 255));
        EmpList.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "S.NO", "EmpId", "Start Reading", "End Reading", "Date Of Entry", "Price/km", "Total"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        EmpList.setRowHeight(28);
        EmpList.setSelectionBackground(new java.awt.Color(0, 0, 0));
        EmpList.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(EmpList);

        jPanel7.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, 950, 280));

        jCheckBox1.setBackground(new java.awt.Color(255, 255, 255));
        jCheckBox1.setForeground(new java.awt.Color(51, 51, 255));
        jCheckBox1.setText("Apply Date Filter");
        jCheckBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox1ActionPerformed(evt);
            }
        });
        jPanel7.add(jCheckBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 0, -1, -1));

        txttotal.setFont(new java.awt.Font("Trebuchet MS", 2, 22)); // NOI18N
        txttotal.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel7.add(txttotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 330, 180, 40));

        jLabel12.setFont(new java.awt.Font("Trebuchet MS", 2, 22)); // NOI18N
        jLabel12.setText("Total      :");
        jPanel7.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 340, 120, -1));

        jPanel1.add(jPanel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 220, 990, 380));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGES/SIDE2.jpg"))); // NOI18N
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 650, 1250, 30));

        jLabel13.setFont(new java.awt.Font("Trebuchet MS", 2, 22)); // NOI18N
        jLabel13.setText("Employee Id           :");
        jPanel1.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 170, 220, -1));

        jLabel14.setFont(new java.awt.Font("Trebuchet MS", 2, 22)); // NOI18N
        jLabel14.setText("Employee Id           :");
        jPanel1.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 170, 220, -1));

        scbar.setViewportView(jPanel1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(scbar, javax.swing.GroupLayout.DEFAULT_SIZE, 1266, Short.MAX_VALUE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(scbar, javax.swing.GroupLayout.DEFAULT_SIZE, 664, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnQuitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnQuitActionPerformed
        int ans;
        ans=JOptionPane.showConfirmDialog(null, "Are u sure ?","Quitting!",JOptionPane.YES_NO_OPTION,JOptionPane.QUESTION_MESSAGE);
        if(ans==JOptionPane.YES_OPTION)
        {
            dbutil.closeConnection();
            System.exit(0);
        }    
        // TODO add your handling code here:

        // TODO add your handling code here:
    }//GEN-LAST:event_btnQuitActionPerformed

    private void jcempidActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcempidActionPerformed
       

        // TODO add your handling code here:
    }//GEN-LAST:event_jcempidActionPerformed

    private void btnbackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnbackActionPerformed
this.dispose();
new AdminOptionFrame().setVisible(true);




        // TODO add your handling code here:
    }//GEN-LAST:event_btnbackActionPerformed

    private void btnshowrecordsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnshowrecordsActionPerformed
  try
{
   ArrayList<fuel> am ; 
    am = fuelDao.getFuelEntry();
    if(am==null)
    {
         JOptionPane.showMessageDialog(null,"No Record Found","Empty Table",JOptionPane.INFORMATION_MESSAGE);
        return ;
    }
    else
    {
    int i=0;
    model = (DefaultTableModel)EmpList.getModel();

    model.setRowCount(0);
    EmpList.setRowHeight(21);
    Iterator it = am.iterator();
    while(it.hasNext())
    {
     
     fuel emp = (fuel)it.next();
     if(emp.getEmpId().equalsIgnoreCase(jcempid.getSelectedItem().toString())){
         ++i;
    Object[] row = {i,emp.getEmpId(),emp.getStartR(),emp.getFinR(),emp.getDate(),emp.getPrice(),emp.getTotal()};
    model.addRow(row);
     }
    
}
    if(model.getRowCount()==0){
        JOptionPane.showMessageDialog(null,"No Record Found for this id","Empty Table",JOptionPane.INFORMATION_MESSAGE);
        return ; 
    }
    } 
}
catch(Throwable ex)
{
    JOptionPane.showMessageDialog(null,"Data is not successfully showed\n Error in SQL part","Failure",JOptionPane.ERROR_MESSAGE);

            ex.printStackTrace();
   
    
}// TODO add your handling code here:








        // TODO add your handling code here:
    }//GEN-LAST:event_btnshowrecordsActionPerformed

    private void jCheckBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox1ActionPerformed
if(jCheckBox1.isSelected()) {
    
    if(EmpList.getRowCount()>0)
    {
        datefilter d = new datefilter(this,true);  
d.setVisible(true);

        
           double count =0;
           for(int i =0;i<model.getRowCount();i++){
               Date di = (Date)model.getValueAt(i, 4);
               if((di.after(d1) && di.before(d2)) || (di.equals(d1) || di.equals(d2)))
               {
                   count = (double)model.getValueAt(i, 6) +count;
               }
           }
                  txttotal.setText(count+"");
    }
    else{
     JOptionPane.showMessageDialog(null,"Data is Not Available to use filter","EMPTY DATA",JOptionPane.ERROR_MESSAGE);
    jCheckBox1.setSelected(false);
    }
        }
if(!jCheckBox1.isSelected())
    txttotal.setText("");
// TODO add your handling code here:
    }//GEN-LAST:event_jCheckBox1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EmpWiseFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EmpWiseFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EmpWiseFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EmpWiseFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EmpWiseFrame().setVisible(true);
            }
        });
   
    
    }
  

    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable EmpList;
    private javax.swing.JButton btnQuit;
    private javax.swing.JButton btnback;
    private javax.swing.JButton btnshowrecords;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JComboBox<String> jcempid;
    private javax.swing.JScrollPane scbar;
    private javax.swing.JTextField txttotal;
    // End of variables declaration//GEN-END:variables
}
