/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package khanaBadosh.Gui;

import java.awt.Dimension;
import java.awt.Image;
import java.awt.Toolkit;
import java.util.ArrayList;
import java.util.Date;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.SwingUtilities;
import javax.swing.UIManager;
import khanaBadosh.Dao.Employees_jobDao;
import khanaBadosh.Dao.fuelDao;
import khanaBadosh.dbutil.dbutil;
import khanaBadosh.pojo.fuel;

/**
 *
 * @author HP
 */
public class FuelFrame extends javax.swing.JFrame {
    private int strtR,FinR;
    private double pricep,total;
    private Date date ;
    private String EmpId ;
    ArrayList<String> al ;
    /**
     * Creates new form FuelFrame
     */
    public FuelFrame() {
        initComponents();
         try {
             Dimension d = Toolkit.getDefaultToolkit().getScreenSize();
         setBounds(0,0,d.width, d.height);
       this.setResizable(false);
   UIManager.setLookAndFeel("com.sun.java.swing.plaf.windows.WindowsLookAndFeel");
   SwingUtilities.updateComponentTreeUI(scbar);
  
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
             SwingUtilities.updateComponentTreeUI(jPanel1);
        } catch (Throwable ex) {
            java.util.logging.Logger.getLogger(ViewFuelFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        this.setLocationRelativeTo(null);
        Toolkit t = Toolkit.getDefaultToolkit();
        Image im = t.getImage(getClass().getResource("/IMAGES/title.jpg"));
        setIconImage(im);
  
Image img = t.getImage(getClass().getResource("/IMAGES/SIDE3.jpg")).getScaledInstance(jLabel5.getWidth(),jLabel5.getHeight(),Image.SCALE_SMOOTH);
ImageIcon icon=new ImageIcon(img);
jLabel5.setIcon(icon);
  img = t.getImage(getClass().getResource("/IMAGES/Untitled-1-copy.jpg")).getScaledInstance(jLabel8.getWidth(),jLabel8.getHeight(),Image.SCALE_SMOOTH);
 icon=new ImageIcon(img);
jLabel8.setIcon(icon);
img = t.getImage(getClass().getResource("/IMAGES/SIDE.jpg")).getScaledInstance(jLabel6.getWidth(),jLabel6.getHeight(),Image.SCALE_SMOOTH);
 icon=new ImageIcon(img);
jLabel6.setIcon(icon);



          try{
            al = Employees_jobDao.getEmpId();
            for(String x:al)
            {
             jcEmpId.addItem(x);
            }
        }
        catch(Throwable th)
        {
            th.printStackTrace();
        }
    

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        scbar = new javax.swing.JScrollPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        txtTotal = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jsStrtR = new javax.swing.JSpinner();
        jsFinR = new javax.swing.JSpinner();
        jLabel3 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jsPriceperkm = new javax.swing.JSpinner();
        jLabel12 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jdDate = new com.toedter.calendar.JDateChooser();
        jButton1 = new javax.swing.JButton();
        jcEmpId = new javax.swing.JComboBox<>();
        jButton3 = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        btnQuit = new javax.swing.JButton();
        btnclear = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("KHANABADOSH EMPLOYEE MANAGEMENT\n");

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGES/SIDE.jpg"))); // NOI18N
        jLabel6.setText("jLabel5");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(940, 0, 290, 560));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGES/SIDE3.jpg"))); // NOI18N
        jLabel5.setText("jLabel5");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 300, 270, 390));

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGES/Untitled-1-copy.jpg"))); // NOI18N
        jLabel8.setText("jLabel8");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 930, 130));

        jPanel7.setBackground(new java.awt.Color(255, 255, 255));
        jPanel7.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "FUEL DEAILS :", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.ABOVE_TOP, new java.awt.Font("Tahoma", 1, 28), new java.awt.Color(255, 153, 0))); // NOI18N
        jPanel7.setForeground(new java.awt.Color(255, 0, 0));
        jPanel7.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtTotal.setEditable(false);
        txtTotal.setBackground(new java.awt.Color(255, 255, 255));
        txtTotal.setFont(new java.awt.Font("Trebuchet MS", 2, 22)); // NOI18N
        txtTotal.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel7.add(txtTotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 200, 280, -1));

        jLabel2.setFont(new java.awt.Font("Trebuchet MS", 2, 22)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 102, 0));
        jLabel2.setText("STARTING READING     :");
        jLabel2.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jPanel7.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, 270, -1));

        jsStrtR.setFont(new java.awt.Font("Trebuchet MS", 2, 22)); // NOI18N
        jsStrtR.setModel(new javax.swing.SpinnerNumberModel(0, 0, null, 1));
        jsStrtR.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jsStrtR.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jsStrtRStateChanged(evt);
            }
        });
        jPanel7.add(jsStrtR, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 50, 270, -1));

        jsFinR.setFont(new java.awt.Font("Trebuchet MS", 2, 22)); // NOI18N
        jsFinR.setModel(new javax.swing.SpinnerNumberModel(0, 0, null, 1));
        jsFinR.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jsFinR.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jsStrtRStateChanged(evt);
            }
        });
        jPanel7.add(jsFinR, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 100, 270, -1));

        jLabel3.setFont(new java.awt.Font("Trebuchet MS", 2, 22)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 102, 0));
        jLabel3.setText("FINAL READING           :");
        jPanel7.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 100, 270, -1));

        jLabel9.setFont(new java.awt.Font("Trebuchet MS", 2, 22)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 102, 0));
        jLabel9.setText("PRICE PER KM            :");
        jPanel7.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 150, 260, -1));

        jsPriceperkm.setFont(new java.awt.Font("Trebuchet MS", 2, 22)); // NOI18N
        jsPriceperkm.setModel(new javax.swing.SpinnerNumberModel(0.0d, 0.0d, null, 0.5d));
        jsPriceperkm.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jsPriceperkm.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jsPriceperkmStateChanged(evt);
            }
        });
        jsPriceperkm.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                jsPriceperkmMouseMoved(evt);
            }
        });
        jsPriceperkm.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jsPriceperkmMouseExited(evt);
            }
        });
        jsPriceperkm.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jsPriceperkmKeyTyped(evt);
            }
        });
        jPanel7.add(jsPriceperkm, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 150, 270, -1));

        jLabel12.setFont(new java.awt.Font("Trebuchet MS", 2, 22)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 102, 0));
        jLabel12.setText("TOTAL FUEL (in Rs.)   :");
        jPanel7.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 200, 250, -1));

        jLabel11.setFont(new java.awt.Font("Trebuchet MS", 2, 22)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 102, 0));
        jLabel11.setText("Date                         :");
        jPanel7.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 250, 260, -1));

        jdDate.setBackground(new java.awt.Color(255, 255, 255));
        jdDate.setDateFormatString("dd MMM,yyy");
        jdDate.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jPanel7.add(jdDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 250, 270, 40));

        jButton1.setBackground(new java.awt.Color(204, 0, 0));
        jButton1.setFont(new java.awt.Font("Tahoma", 3, 20)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("ADD FUEL DETAILS");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel7.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 420, 240, 40));

        jcEmpId.setFont(new java.awt.Font("Trebuchet MS", 2, 22)); // NOI18N
        jcEmpId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcEmpIdActionPerformed(evt);
            }
        });
        jPanel7.add(jcEmpId, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 320, 270, -1));

        jButton3.setBackground(new java.awt.Color(204, 0, 0));
        jButton3.setFont(new java.awt.Font("Tahoma", 3, 20)); // NOI18N
        jButton3.setForeground(new java.awt.Color(255, 255, 255));
        jButton3.setText("BACK");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel7.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 420, 110, 40));

        jLabel10.setFont(new java.awt.Font("Trebuchet MS", 2, 22)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 102, 0));
        jLabel10.setText("EMPLOYEE ID             :");
        jPanel7.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 310, 260, -1));

        jPanel1.add(jPanel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 130, 670, 490));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGES/tenor (1).gif"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 130, 220, 180));

        btnQuit.setBackground(new java.awt.Color(204, 0, 0));
        btnQuit.setFont(new java.awt.Font("Tahoma", 3, 20)); // NOI18N
        btnQuit.setForeground(new java.awt.Color(255, 255, 255));
        btnQuit.setText("QUIT");
        btnQuit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnQuitActionPerformed(evt);
            }
        });
        jPanel1.add(btnQuit, new org.netbeans.lib.awtextra.AbsoluteConstraints(1110, 630, 110, 40));

        btnclear.setBackground(new java.awt.Color(204, 0, 0));
        btnclear.setFont(new java.awt.Font("Tahoma", 3, 20)); // NOI18N
        btnclear.setForeground(new java.awt.Color(255, 255, 255));
        btnclear.setText("CLEAR");
        btnclear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnclearActionPerformed(evt);
            }
        });
        jPanel1.add(btnclear, new org.netbeans.lib.awtextra.AbsoluteConstraints(970, 630, 120, 40));

        scbar.setViewportView(jPanel1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(scbar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 1214, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(scbar, javax.swing.GroupLayout.DEFAULT_SIZE, 690, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jsPriceperkmKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jsPriceperkmKeyTyped



        



        // TODO add your handling code here:
    }//GEN-LAST:event_jsPriceperkmKeyTyped

    private void jsPriceperkmMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jsPriceperkmMouseExited
       
        // TODO add your handling code here:
    }//GEN-LAST:event_jsPriceperkmMouseExited

    private void jsPriceperkmMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jsPriceperkmMouseMoved
        // TODO add your handling code here:
    }//GEN-LAST:event_jsPriceperkmMouseMoved

    private void jsPriceperkmStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jsPriceperkmStateChanged
    strtR = Integer.parseInt(jsStrtR.getValue().toString());
FinR = Integer.parseInt(jsFinR.getValue().toString());

pricep = Double.parseDouble(jsPriceperkm.getValue().toString());
if(strtR >= FinR || pricep < 1)
{
 JOptionPane.showMessageDialog(null,"start Reading must be smaller than Final Reading\n Note : Price Per Km cannot be zero","ERROR!!",JOptionPane.ERROR_MESSAGE);
 txtTotal.setText("");
 return ;    
}
total = (FinR - strtR)*pricep ;
txtTotal.setText(total+"");    // TODO add your handling code here:
    }//GEN-LAST:event_jsPriceperkmStateChanged

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
if(txtTotal.getText().isEmpty()||jdDate.getDate()==null)
{
 JOptionPane.showMessageDialog(null,"Please Fill All the Fields","ERROR!!",JOptionPane.ERROR_MESSAGE);
   return ;
}
EmpId = jcEmpId.getSelectedItem().toString();
fuel obj = new fuel();
obj.setStartR(strtR);
obj.setFinR(FinR);
obj.setPrice(pricep);
obj.setEmpId(EmpId);
obj.setTotal(total);
date = jdDate.getDate();
obj.setDate(date);
try
{
 if(fuelDao.AddFuelEntry(obj)){
     JOptionPane.showMessageDialog(null,"Data successfully added to the database","Success",JOptionPane.INFORMATION_MESSAGE);
 btnclearActionPerformed(evt);
 }
 
}
catch(Throwable th)
{
 JOptionPane.showMessageDialog(null,"Contanct Master Admin \n Error in DB"+th,"ERROR!!",JOptionPane.ERROR_MESSAGE);
    
}



// TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void btnclearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnclearActionPerformed

        this.dispose();
        new FuelFrame().setVisible(true);
// TODO add your handling code here:
    }//GEN-LAST:event_btnclearActionPerformed

    private void btnQuitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnQuitActionPerformed
 int ans;
        ans=JOptionPane.showConfirmDialog(null, "Are u sure ?","Quitting!",JOptionPane.YES_NO_OPTION,JOptionPane.QUESTION_MESSAGE);
        if(ans==JOptionPane.YES_OPTION)
        {
            dbutil.closeConnection();
            System.exit(0);
        }        // TODO add your handling code here:
    

        // TODO add your handling code here:
    }//GEN-LAST:event_btnQuitActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
this.dispose();
new AdminOptionFrame().setVisible(true);


        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jsStrtRStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jsStrtRStateChanged
     strtR = Integer.parseInt(jsStrtR.getValue().toString());
FinR = Integer.parseInt(jsFinR.getValue().toString());

pricep = Double.parseDouble(jsPriceperkm.getValue().toString());
if(strtR >= FinR || pricep==0.0)
{
 JOptionPane.showMessageDialog(null,"start Reading must be smaller than Final Reading\n Note : Price Per Km cannot be zero","ERROR!!",JOptionPane.ERROR_MESSAGE);
 txtTotal.setText("");
 return ;    
}
total = (FinR - strtR)*pricep ;
txtTotal.setText(total+"");    // TODO add your handling code here:
    }//GEN-LAST:event_jsStrtRStateChanged

    private void jcEmpIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcEmpIdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jcEmpIdActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FuelFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FuelFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FuelFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FuelFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FuelFrame().setVisible(true);
            }
        });
        
    }

    @Override
    public int getDefaultCloseOperation() {
        dbutil.closeConnection();
        return super.getDefaultCloseOperation(); //To change body of generated methods, choose Tools | Templates.
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnQuit;
    private javax.swing.JButton btnclear;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JComboBox<String> jcEmpId;
    private com.toedter.calendar.JDateChooser jdDate;
    private javax.swing.JSpinner jsFinR;
    private javax.swing.JSpinner jsPriceperkm;
    private javax.swing.JSpinner jsStrtR;
    private javax.swing.JScrollPane scbar;
    private javax.swing.JTextField txtTotal;
    // End of variables declaration//GEN-END:variables
}
