/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package khanaBadosh.Gui;


import java.awt.Dimension;
import java.awt.Image;
import java.awt.Toolkit;
import java.util.ArrayList;
import java.util.Iterator;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.SwingUtilities;
import javax.swing.UIManager;
import khanaBadosh.Dao.Employees_jobDao;
import khanaBadosh.Dao.fuelDao;
import khanaBadosh.dbutil.dbutil;
import khanaBadosh.pojo.fuel;

/**
 *
 * @author HP
 */
public class FuelEditingFrame extends javax.swing.JFrame {
   /**  @Override
    public void setDefaultCloseOperation(int i) {
        dbutil.closeConnection();
        super.setDefaultCloseOperation(i); //To change body of generated methods, choose Tools | Templates.
    }**/
ArrayList<String> al ;
int str,fin;
double price , total;
java.sql.Date d1;
    /**
     * Creates new form FuelEditingFrame
     */
    public FuelEditingFrame() {
        initComponents();
         try {
             Dimension d = Toolkit.getDefaultToolkit().getScreenSize();
         setBounds(0,0,d.width, d.height);
       this.setResizable(false);
   UIManager.setLookAndFeel("com.sun.java.swing.plaf.windows.WindowsLookAndFeel");
   SwingUtilities.updateComponentTreeUI(scbar);
  
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
             SwingUtilities.updateComponentTreeUI(jPanel1);
        } catch (Throwable ex) {
            java.util.logging.Logger.getLogger(ViewFuelFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
         Toolkit t = Toolkit.getDefaultToolkit();
        Image im = t.getImage(getClass().getResource("/IMAGES/title.jpg"));
        setIconImage(im);
  
Image img = t.getImage(getClass().getResource("/IMAGES/SIDE3.jpg")).getScaledInstance(jLabel5.getWidth(),jLabel5.getHeight(),Image.SCALE_SMOOTH);
ImageIcon icon=new ImageIcon(img);
jLabel5.setIcon(icon);
  img = t.getImage(getClass().getResource("/IMAGES/Untitled-1-copy.jpg")).getScaledInstance(jLabel8.getWidth(),jLabel8.getHeight(),Image.SCALE_SMOOTH);
 icon=new ImageIcon(img);
jLabel8.setIcon(icon);


        try{
            this.setLocationRelativeTo(null);
             
            al = Employees_jobDao.getEmpId();
            for(String x:al)
            {
             jcempid.addItem(x);
            }
        }
        catch(Throwable th)
        {
            th.printStackTrace();
        }
    
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        scbar = new javax.swing.JScrollPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        txtTotal = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jsStrtR = new javax.swing.JSpinner();
        jsFinR = new javax.swing.JSpinner();
        jLabel3 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jsPriceperkm = new javax.swing.JSpinner();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jdDate = new com.toedter.calendar.JDateChooser();
        jcempid = new javax.swing.JComboBox<>();
        jLabel12 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        btnQuit = new javax.swing.JButton();
        btnShowDetail = new javax.swing.JButton();
        btnreset = new javax.swing.JButton();
        btnback = new javax.swing.JButton();
        btndelete = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGES/tenor (1).gif"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 170, -1, 180));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGES/SIDE3.jpg"))); // NOI18N
        jLabel5.setText("jLabel5");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 350, 240, 330));

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGES/Untitled-1-copy.jpg"))); // NOI18N
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 0, 1200, 160));

        jPanel7.setBackground(new java.awt.Color(255, 255, 255));
        jPanel7.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "EDIT FUEL DEAILS :", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.ABOVE_TOP, new java.awt.Font("Tahoma", 1, 28), new java.awt.Color(255, 153, 0))); // NOI18N
        jPanel7.setForeground(new java.awt.Color(255, 0, 0));
        jPanel7.setOpaque(false);
        jPanel7.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtTotal.setEditable(false);
        txtTotal.setBackground(new java.awt.Color(255, 255, 255));
        txtTotal.setFont(new java.awt.Font("Arial Unicode MS", 1, 24)); // NOI18N
        txtTotal.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel7.add(txtTotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 290, 280, -1));

        jLabel2.setFont(new java.awt.Font("Trebuchet MS", 2, 22)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 102, 0));
        jLabel2.setText("STARTING READING       :");
        jLabel2.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jPanel7.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 140, 270, -1));

        jsStrtR.setFont(new java.awt.Font("Arial Unicode MS", 1, 24)); // NOI18N
        jsStrtR.setModel(new javax.swing.SpinnerNumberModel(0, 0, null, 1));
        jsStrtR.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jsStrtR.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jsPriceperkmStateChanged(evt);
            }
        });
        jPanel7.add(jsStrtR, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 140, 240, 40));

        jsFinR.setFont(new java.awt.Font("Arial Unicode MS", 1, 24)); // NOI18N
        jsFinR.setModel(new javax.swing.SpinnerNumberModel(0, 0, null, 1));
        jsFinR.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jsFinR.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jsPriceperkmStateChanged(evt);
            }
        });
        jPanel7.add(jsFinR, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 220, 240, 40));

        jLabel3.setFont(new java.awt.Font("Trebuchet MS", 2, 22)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 102, 0));
        jLabel3.setText("FINAL READING            :");
        jPanel7.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 220, 250, -1));

        jLabel9.setFont(new java.awt.Font("Trebuchet MS", 2, 22)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 102, 0));
        jLabel9.setText("PRICE PER KM      :");
        jPanel7.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 230, 200, -1));

        jsPriceperkm.setFont(new java.awt.Font("Arial Unicode MS", 1, 24)); // NOI18N
        jsPriceperkm.setModel(new javax.swing.SpinnerNumberModel(1.5d, 1.5d, null, 0.5d));
        jsPriceperkm.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jsPriceperkm.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jsPriceperkmStateChanged(evt);
            }
        });
        jsPriceperkm.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                jsPriceperkmMouseMoved(evt);
            }
        });
        jsPriceperkm.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jsPriceperkmMouseExited(evt);
            }
        });
        jPanel7.add(jsPriceperkm, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 230, 230, 40));

        jLabel10.setFont(new java.awt.Font("Trebuchet MS", 2, 22)); // NOI18N
        jLabel10.setText("SELECT EMPLOYEE ID     :");
        jPanel7.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, 260, -1));

        jLabel11.setFont(new java.awt.Font("Trebuchet MS", 2, 22)); // NOI18N
        jLabel11.setText("SELECT DATE     :");
        jPanel7.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 70, 180, -1));

        jdDate.setBackground(new java.awt.Color(255, 255, 255));
        jdDate.setDateFormatString("dd MMM,yyy");
        jdDate.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jPanel7.add(jdDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 70, 230, 40));

        jcempid.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jcempid.setOpaque(false);
        jcempid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcempidActionPerformed(evt);
            }
        });
        jPanel7.add(jcempid, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 60, 240, -1));

        jLabel12.setFont(new java.awt.Font("Trebuchet MS", 2, 22)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 102, 0));
        jLabel12.setText("TOTAL FUEL (in Rs.)   :");
        jPanel7.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 290, 250, -1));

        jButton1.setBackground(new java.awt.Color(204, 0, 0));
        jButton1.setFont(new java.awt.Font("Tahoma", 3, 20)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("UPDATE FUEL DETAILS");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel7.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 370, 270, 30));

        btnQuit.setBackground(new java.awt.Color(255, 102, 0));
        btnQuit.setFont(new java.awt.Font("Tahoma", 3, 20)); // NOI18N
        btnQuit.setForeground(new java.awt.Color(255, 255, 255));
        btnQuit.setText("QUIT");
        btnQuit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnQuitActionPerformed(evt);
            }
        });
        jPanel7.add(btnQuit, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 430, 130, 30));

        btnShowDetail.setBackground(new java.awt.Color(204, 0, 0));
        btnShowDetail.setFont(new java.awt.Font("Tahoma", 3, 20)); // NOI18N
        btnShowDetail.setForeground(new java.awt.Color(255, 255, 255));
        btnShowDetail.setText("SHOW DETAILS");
        btnShowDetail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnShowDetailActionPerformed(evt);
            }
        });
        jPanel7.add(btnShowDetail, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 150, 250, 40));

        btnreset.setBackground(new java.awt.Color(204, 0, 0));
        btnreset.setFont(new java.awt.Font("Tahoma", 3, 20)); // NOI18N
        btnreset.setForeground(new java.awt.Color(255, 255, 255));
        btnreset.setText("RESET");
        btnreset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnresetActionPerformed(evt);
            }
        });
        jPanel7.add(btnreset, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 430, 130, 30));

        btnback.setBackground(new java.awt.Color(255, 102, 0));
        btnback.setFont(new java.awt.Font("Tahoma", 3, 20)); // NOI18N
        btnback.setForeground(new java.awt.Color(255, 255, 255));
        btnback.setText("BACK");
        btnback.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnbackActionPerformed(evt);
            }
        });
        jPanel7.add(btnback, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 430, 130, 30));

        btndelete.setBackground(new java.awt.Color(204, 0, 0));
        btndelete.setFont(new java.awt.Font("Tahoma", 3, 20)); // NOI18N
        btndelete.setForeground(new java.awt.Color(255, 255, 255));
        btndelete.setText("DELETE ENTRY");
        btndelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btndeleteActionPerformed(evt);
            }
        });
        jPanel7.add(btndelete, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 370, 180, 30));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGES/SIDE2.jpg"))); // NOI18N
        jPanel7.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 430, 920, 30));

        jPanel1.add(jPanel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(266, 178, 964, 518));

        scbar.setViewportView(jPanel1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(scbar, javax.swing.GroupLayout.DEFAULT_SIZE, 1198, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(scbar, javax.swing.GroupLayout.DEFAULT_SIZE, 696, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jsPriceperkmMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jsPriceperkmMouseMoved
        // TODO add your handling code here:
    }//GEN-LAST:event_jsPriceperkmMouseMoved

   

    private void jsPriceperkmMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jsPriceperkmMouseExited

        // TODO add your handling code here:
    }//GEN-LAST:event_jsPriceperkmMouseExited

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
      if(txtTotal.getText().isEmpty()||jdDate.getDate()==null)
        {
            JOptionPane.showMessageDialog(null,"Please Fill All the Fields","ERROR!!",JOptionPane.ERROR_MESSAGE);
            return ;
        }
        String EmpId = jcempid.getSelectedItem().toString();
        fuel obj = new fuel();
        obj.setStartR(str);
        obj.setFinR(fin);
        obj.setPrice(price);
        obj.setEmpId(EmpId);
        obj.setTotal(total);
        obj.setDate(d1);
        try
        {
            if(fuelDao.UpdateFuelEntry(obj)){
                JOptionPane.showMessageDialog(null,"Fuel Entry Successfully Updated.","Success",JOptionPane.INFORMATION_MESSAGE);
               
            }

        }
        catch(Throwable th)
        {
            JOptionPane.showMessageDialog(null,"Contanct Master Admin \n Error in DB"+th,"ERROR!!",JOptionPane.ERROR_MESSAGE);

        }

        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void btnShowDetailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnShowDetailActionPerformed
     if(jdDate.getDate()==null)
     {
  JOptionPane.showMessageDialog(null,"Please Select a Valid Date","No Date Selected!!",JOptionPane.ERROR_MESSAGE);
  
     }
     else
     {
           try
{
   ArrayList<fuel> am ; 
    am = fuelDao.getFuelEntry();
    if(am==null)
    {
         JOptionPane.showMessageDialog(null,"No Record Found","Empty Records",JOptionPane.INFORMATION_MESSAGE);
        return ;
    }
    else
    {
   
     Iterator it = am.iterator();
     int count =0;
    while(it.hasNext())
    {
     
     fuel emp = (fuel)it.next();
     long mili = jdDate.getDate().getTime();
   d1 = new java.sql.Date(mili);
  
     if(emp.getEmpId().equalsIgnoreCase(jcempid.getSelectedItem().toString())&&(emp.getDate().toString().equalsIgnoreCase(d1.toString()))){
         jsFinR.setValue(emp.getFinR());
          jsPriceperkm.setValue(emp.getPrice());
          txtTotal.setText(emp.getTotal()+"");
       
 jsStrtR.setValue(emp.getStartR());
 jdDate.setEnabled(false);
        count =1;
      }
    
}
    if(count==0){
     JOptionPane.showMessageDialog(null,"No Record Found \n Please check id/date","Empty Records",JOptionPane.INFORMATION_MESSAGE);
     jsStrtR.setValue(0);
        jsFinR.setValue(0);
       jsPriceperkm.setValue(0);
       txtTotal.setText("");
     
    }
    
    } 
}
catch(Throwable ex)
{
    JOptionPane.showMessageDialog(null,"Data is not successfully showed\n Error in SQL part","Failure",JOptionPane.ERROR_MESSAGE);

            ex.printStackTrace();
   
    
}// TODO add your handling code here:

     }
      
        // TODO add your handling code here:
    }//GEN-LAST:event_btnShowDetailActionPerformed

    private void btnQuitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnQuitActionPerformed
        int ans;
        ans=JOptionPane.showConfirmDialog(null, "Are u sure ?","Quitting!",JOptionPane.YES_NO_OPTION,JOptionPane.QUESTION_MESSAGE);
        if(ans==JOptionPane.YES_OPTION)
        {
            dbutil.closeConnection();
            System.exit(0);
        }        // TODO add your handling code here:

        // TODO add your handling code here:
    }//GEN-LAST:event_btnQuitActionPerformed

    private void jcempidActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcempidActionPerformed

        // TODO add your handling code here:
    }//GEN-LAST:event_jcempidActionPerformed

    private void btnresetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnresetActionPerformed
 jdDate.setEnabled(true);
 jsStrtR.setValue(0);
 jsFinR.setValue(0);
 jsPriceperkm.setValue(1);
 txtTotal.setText("");

// TODO add your handling code here:
    }//GEN-LAST:event_btnresetActionPerformed

    private void jsPriceperkmStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jsPriceperkmStateChanged
 
        str =  (int)jsStrtR.getValue();
               
        fin =  (int)jsFinR.getValue();
        price = Double.parseDouble(jsPriceperkm.getValue()+"");
     
         if(str > fin)
        {
            JOptionPane.showMessageDialog(null,"start Reading must be smaller than Final Reading\n Note : Price Per Km cannot be zero","ERROR!!",JOptionPane.ERROR_MESSAGE);
            txtTotal.setText("");
            return ;
        }
         total = (fin - str)*price ;
        txtTotal.setText(total+""); 
            
        


// TODO add your handling code here:
    }//GEN-LAST:event_jsPriceperkmStateChanged

    private void btnbackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnbackActionPerformed
this.dispose();
        new AdminOptionFrame().setVisible(true);
       
            
        
// TODO add your handling code here:
    }//GEN-LAST:event_btnbackActionPerformed

    private void btndeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btndeleteActionPerformed
      if(txtTotal.getText().isEmpty()||jdDate.getDate()==null)
        {
            JOptionPane.showMessageDialog(null,"Please Select Valid Record","ERROR!!",JOptionPane.ERROR_MESSAGE);
            return ;
        }
        String EmpId = jcempid.getSelectedItem().toString();
        fuel obj = new fuel();
        obj.setStartR(str);
        obj.setFinR(fin);
        obj.setPrice(price);
        obj.setEmpId(EmpId);
        obj.setTotal(total);
        obj.setDate(d1);
        try
        {
            if(fuelDao.DeleteFuelEntry(obj)){
                JOptionPane.showMessageDialog(null,"Fuel Entry Successfully Deleted.","DELETED",JOptionPane.INFORMATION_MESSAGE);
               
            }

        }
        catch(Throwable th)
        {
            JOptionPane.showMessageDialog(null,"Contanct Master Admin \n Error in DB"+th,"ERROR!!",JOptionPane.ERROR_MESSAGE);

        }

      
        

// TODO add your handling code here:
    }//GEN-LAST:event_btndeleteActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FuelEditingFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FuelEditingFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FuelEditingFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FuelEditingFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FuelEditingFrame().setVisible(true);
            }
        });
        
    }
   

   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnQuit;
    private javax.swing.JButton btnShowDetail;
    private javax.swing.JButton btnback;
    private javax.swing.JButton btndelete;
    private javax.swing.JButton btnreset;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JComboBox<String> jcempid;
    private com.toedter.calendar.JDateChooser jdDate;
    private javax.swing.JSpinner jsFinR;
    private javax.swing.JSpinner jsPriceperkm;
    private javax.swing.JSpinner jsStrtR;
    private javax.swing.JScrollPane scbar;
    private javax.swing.JTextField txtTotal;
    // End of variables declaration//GEN-END:variables
}
