/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package khanaBadosh.Gui;

import java.awt.Dimension;
import java.awt.Image;
import java.awt.Toolkit;
import java.util.ArrayList;
import java.util.Date;
import javax.swing.ImageIcon;
import javax.swing.JComboBox;
import javax.swing.JOptionPane;
import javax.swing.SwingUtilities;
import javax.swing.UIManager;
import khanaBadosh.Dao.Employees_jobDao;
import khanaBadosh.dbutil.dbutil;
import khanaBadosh.pojo.employees_job;
import khanaBadosh.pojo.invoice;

/**
 *
 * @author HP
 */
public class GenerateInvoice extends javax.swing.JFrame {
int ded , total , net;
ArrayList<String> al ;
employees_job emp;

    /**
     * Creates new form GenerateInvoice
     */
    public GenerateInvoice() {
        initComponents();
         try {
             Dimension d = Toolkit.getDefaultToolkit().getScreenSize();
         setBounds(0,0,d.width, d.height);
     this.setResizable(false);
     UIManager.setLookAndFeel("com.sun.java.swing.plaf.windows.WindowsLookAndFeel");
   SwingUtilities.updateComponentTreeUI(scbar);
  
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
             SwingUtilities.updateComponentTreeUI(jPanel2);
        } catch (Throwable ex) {
            java.util.logging.Logger.getLogger(ViewFuelFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        this.setLocationRelativeTo(null);
        Toolkit t = Toolkit.getDefaultToolkit();
        Image im = t.getImage(getClass().getResource("/IMAGES/title.jpg"));
        setIconImage(im);
  
        try{
            al = Employees_jobDao.getEmpId();
            for(String x:al)
            {
             jcempid.addItem(x);
            }
        }
        catch(Throwable th)
        {
            th.printStackTrace();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        scbar = new javax.swing.JScrollPane();
        jPanel2 = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        txtname = new javax.swing.JTextField();
        jLabel22 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        txtdep = new javax.swing.JTextField();
        jLabel29 = new javax.swing.JLabel();
        txtdesi = new javax.swing.JTextField();
        jLabel30 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        jLabel34 = new javax.swing.JLabel();
        jcempid = new javax.swing.JComboBox<>();
        jLabel35 = new javax.swing.JLabel();
        jLabel36 = new javax.swing.JLabel();
        jLabel37 = new javax.swing.JLabel();
        jLabel38 = new javax.swing.JLabel();
        jyr = new com.toedter.calendar.JYearChooser();
        jmnth = new com.toedter.calendar.JMonthChooser();
        txtbasics = new javax.swing.JTextField();
        jsconf = new javax.swing.JSpinner();
        jsconv = new javax.swing.JSpinner();
        jshra = new javax.swing.JSpinner();
        jsinc = new javax.swing.JSpinner();
        jsbonus = new javax.swing.JSpinner();
        jsallow = new javax.swing.JSpinner();
        jsdays = new javax.swing.JSpinner();
        jsleave = new javax.swing.JSpinner();
        jspf = new javax.swing.JSpinner();
        jspro = new javax.swing.JSpinner();
        jsinsu = new javax.swing.JSpinner();
        jsadv = new javax.swing.JSpinner();
        jPanel3 = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        txttotalded = new javax.swing.JTextField();
        jLabel42 = new javax.swing.JLabel();
        txttotaladd = new javax.swing.JTextField();
        jLabel43 = new javax.swing.JLabel();
        txtnetsal = new javax.swing.JTextField();
        txtgross = new javax.swing.JTextField();
        txtjoin = new com.toedter.calendar.JDateChooser();
        btnclear = new javax.swing.JButton();
        pic = new javax.swing.JLabel();
        btngenerate = new javax.swing.JButton();
        btnquit = new javax.swing.JButton();
        btnback = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 51, 0), 1, true), "FILL DETAILS OF INVOICE\n", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Tahoma", 1, 24), new java.awt.Color(255, 102, 0))); // NOI18N
        jPanel2.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                jPanel2MouseMoved(evt);
            }
        });
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel12.setFont(new java.awt.Font("Trebuchet MS", 2, 22)); // NOI18N
        jLabel12.setText("Employee Id           :");
        jPanel2.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, 220, -1));

        jLabel13.setFont(new java.awt.Font("Trebuchet MS", 2, 22)); // NOI18N
        jLabel13.setText("Employee Name       :");
        jPanel2.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 40, 230, -1));

        jLabel14.setFont(new java.awt.Font("Trebuchet MS", 2, 22)); // NOI18N
        jLabel14.setText("PF                          :");
        jPanel2.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 240, 230, -1));

        jLabel21.setFont(new java.awt.Font("Trebuchet MS", 2, 22)); // NOI18N
        jLabel21.setText("Proffesion Tax          :  ");
        jPanel2.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 280, -1, -1));

        txtname.setEditable(false);
        txtname.setBackground(new java.awt.Color(255, 255, 255));
        txtname.setFont(new java.awt.Font("Trebuchet MS", 2, 22)); // NOI18N
        txtname.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel2.add(txtname, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 40, 270, 30));

        jLabel22.setFont(new java.awt.Font("Trebuchet MS", 2, 22)); // NOI18N
        jLabel22.setText("Conveyanced Fixed     :");
        jPanel2.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 280, 240, -1));

        jLabel24.setFont(new java.awt.Font("Trebuchet MS", 2, 22)); // NOI18N
        jLabel24.setText("Insurance                 :");
        jPanel2.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 340, -1, -1));

        jLabel25.setFont(new java.awt.Font("Trebuchet MS", 2, 22)); // NOI18N
        jLabel25.setText("Special Allowance      :");
        jPanel2.add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 440, 240, -1));

        jLabel26.setFont(new java.awt.Font("Trebuchet MS", 2, 22)); // NOI18N
        jLabel26.setText(" Bonus                       :");
        jPanel2.add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 490, 240, -1));

        jLabel28.setFont(new java.awt.Font("Trebuchet MS", 2, 22)); // NOI18N
        jLabel28.setText("Department           :");
        jPanel2.add(jLabel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 90, 210, -1));

        txtdep.setEditable(false);
        txtdep.setBackground(new java.awt.Color(255, 255, 255));
        txtdep.setFont(new java.awt.Font("Trebuchet MS", 2, 22)); // NOI18N
        txtdep.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        txtdep.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtdepActionPerformed(evt);
            }
        });
        jPanel2.add(txtdep, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 90, 290, -1));

        jLabel29.setFont(new java.awt.Font("Trebuchet MS", 2, 22)); // NOI18N
        jLabel29.setText("Designation             :");
        jPanel2.add(jLabel29, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 90, 230, -1));

        txtdesi.setEditable(false);
        txtdesi.setBackground(new java.awt.Color(255, 255, 255));
        txtdesi.setFont(new java.awt.Font("Trebuchet MS", 2, 22)); // NOI18N
        txtdesi.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        txtdesi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtdesiActionPerformed(evt);
            }
        });
        jPanel2.add(txtdesi, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 90, 270, -1));

        jLabel30.setFont(new java.awt.Font("Trebuchet MS", 2, 22)); // NOI18N
        jLabel30.setText("Salary  Month & Year   :");
        jPanel2.add(jLabel30, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 140, 250, -1));

        jLabel31.setFont(new java.awt.Font("Trebuchet MS", 2, 22)); // NOI18N
        jLabel31.setText("Worked Days           :");
        jPanel2.add(jLabel31, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 140, 220, -1));

        jLabel32.setFont(new java.awt.Font("Trebuchet MS", 2, 22)); // NOI18N
        jLabel32.setText("Date of Joining           :");
        jPanel2.add(jLabel32, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 190, 240, 30));

        jLabel33.setFont(new java.awt.Font("Trebuchet MS", 2, 22)); // NOI18N
        jLabel33.setText("Leaves                    :");
        jPanel2.add(jLabel33, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 190, 220, 30));

        jLabel34.setFont(new java.awt.Font("Trebuchet MS", 2, 22)); // NOI18N
        jLabel34.setText("Basics                       :");
        jPanel2.add(jLabel34, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 240, 250, -1));

        jcempid.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jcempid.setOpaque(false);
        jcempid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcempidActionPerformed(evt);
            }
        });
        jPanel2.add(jcempid, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 40, 290, -1));

        jLabel35.setFont(new java.awt.Font("Trebuchet MS", 2, 22)); // NOI18N
        jLabel35.setText("Advance                  :");
        jPanel2.add(jLabel35, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 390, -1, -1));

        jLabel36.setFont(new java.awt.Font("Trebuchet MS", 2, 22)); // NOI18N
        jLabel36.setText("Conveyanced Variable  :");
        jPanel2.add(jLabel36, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 340, 250, -1));

        jLabel37.setFont(new java.awt.Font("Trebuchet MS", 2, 22)); // NOI18N
        jLabel37.setText("HRA                           :");
        jPanel2.add(jLabel37, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 390, 240, -1));

        jLabel38.setFont(new java.awt.Font("Trebuchet MS", 2, 22)); // NOI18N
        jLabel38.setText("Incentive                   :");
        jPanel2.add(jLabel38, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 440, 240, -1));
        jPanel2.add(jyr, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 140, 110, 40));

        jmnth.setForeground(new java.awt.Color(255, 0, 0));
        jmnth.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jPanel2.add(jmnth, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 140, -1, 40));

        txtbasics.setFont(new java.awt.Font("Trebuchet MS", 2, 22)); // NOI18N
        txtbasics.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel2.add(txtbasics, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 240, 270, -1));

        jsconf.setFont(new java.awt.Font("Trebuchet MS", 2, 22)); // NOI18N
        jsconf.setModel(new javax.swing.SpinnerNumberModel(0, 0, null, 100));
        jsconf.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jsconf.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jsconfStateChanged(evt);
            }
        });
        jPanel2.add(jsconf, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 290, 270, -1));

        jsconv.setFont(new java.awt.Font("Trebuchet MS", 2, 22)); // NOI18N
        jsconv.setModel(new javax.swing.SpinnerNumberModel(0, 0, null, 100));
        jsconv.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jsconv.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jsconfStateChanged(evt);
            }
        });
        jPanel2.add(jsconv, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 340, 270, -1));

        jshra.setFont(new java.awt.Font("Trebuchet MS", 2, 22)); // NOI18N
        jshra.setModel(new javax.swing.SpinnerNumberModel(0, 0, null, 100));
        jshra.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jshra.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jsconfStateChanged(evt);
            }
        });
        jPanel2.add(jshra, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 390, 270, -1));

        jsinc.setFont(new java.awt.Font("Trebuchet MS", 2, 22)); // NOI18N
        jsinc.setModel(new javax.swing.SpinnerNumberModel(0, 0, null, 100));
        jsinc.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jsinc.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jsconfStateChanged(evt);
            }
        });
        jPanel2.add(jsinc, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 440, 270, -1));

        jsbonus.setFont(new java.awt.Font("Trebuchet MS", 2, 22)); // NOI18N
        jsbonus.setModel(new javax.swing.SpinnerNumberModel(0, 0, null, 100));
        jsbonus.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jsbonus.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jsconfStateChanged(evt);
            }
        });
        jPanel2.add(jsbonus, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 490, 270, -1));

        jsallow.setFont(new java.awt.Font("Trebuchet MS", 2, 22)); // NOI18N
        jsallow.setModel(new javax.swing.SpinnerNumberModel(0, 0, null, 100));
        jsallow.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jsallow.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jsconfStateChanged(evt);
            }
        });
        jPanel2.add(jsallow, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 430, 270, -1));

        jsdays.setFont(new java.awt.Font("Trebuchet MS", 2, 22)); // NOI18N
        jsdays.setModel(new javax.swing.SpinnerNumberModel(30, 0, 30, 1));
        jsdays.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jsdays.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jsdaysStateChanged(evt);
            }
        });
        jPanel2.add(jsdays, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 140, 270, 30));

        jsleave.setFont(new java.awt.Font("Trebuchet MS", 2, 22)); // NOI18N
        jsleave.setModel(new javax.swing.SpinnerNumberModel(0, 0, 30, 1));
        jsleave.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jsleave.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jsleaveStateChanged(evt);
            }
        });
        jPanel2.add(jsleave, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 190, 270, 30));

        jspf.setFont(new java.awt.Font("Trebuchet MS", 2, 22)); // NOI18N
        jspf.setModel(new javax.swing.SpinnerNumberModel(0, 0, null, 100));
        jspf.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jspf.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jsconfStateChanged(evt);
            }
        });
        jPanel2.add(jspf, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 240, 270, -1));

        jspro.setFont(new java.awt.Font("Trebuchet MS", 2, 22)); // NOI18N
        jspro.setModel(new javax.swing.SpinnerNumberModel(0, 0, null, 100));
        jspro.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jspro.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jsconfStateChanged(evt);
            }
        });
        jPanel2.add(jspro, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 280, 270, -1));

        jsinsu.setFont(new java.awt.Font("Trebuchet MS", 2, 22)); // NOI18N
        jsinsu.setModel(new javax.swing.SpinnerNumberModel(0, 0, null, 100));
        jsinsu.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jsinsu.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jsconfStateChanged(evt);
            }
        });
        jPanel2.add(jsinsu, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 330, 270, -1));

        jsadv.setFont(new java.awt.Font("Trebuchet MS", 2, 22)); // NOI18N
        jsadv.setModel(new javax.swing.SpinnerNumberModel(0, 0, null, 100));
        jsadv.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jsadv.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jsconfStateChanged(evt);
            }
        });
        jPanel2.add(jsadv, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 380, 270, -1));

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 51, 0), 1, true), "Net Details\n", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Tahoma", 1, 20), new java.awt.Color(255, 102, 0))); // NOI18N
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel15.setFont(new java.awt.Font("Trebuchet MS", 2, 22)); // NOI18N
        jLabel15.setText("Total Addition       :");
        jPanel3.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, 220, -1));

        jLabel16.setFont(new java.awt.Font("Trebuchet MS", 2, 22)); // NOI18N
        jLabel16.setText("Total Deductions     :");
        jPanel3.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 30, 230, -1));

        txttotalded.setEditable(false);
        txttotalded.setBackground(new java.awt.Color(255, 255, 255));
        txttotalded.setFont(new java.awt.Font("Trebuchet MS", 2, 22)); // NOI18N
        txttotalded.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel3.add(txttotalded, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 30, 310, 30));

        jLabel42.setFont(new java.awt.Font("Trebuchet MS", 2, 22)); // NOI18N
        jLabel42.setText("Gross Salary         :");
        jPanel3.add(jLabel42, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, 210, -1));

        txttotaladd.setEditable(false);
        txttotaladd.setBackground(new java.awt.Color(255, 255, 255));
        txttotaladd.setFont(new java.awt.Font("Trebuchet MS", 2, 22)); // NOI18N
        txttotaladd.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        txttotaladd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txttotaladdActionPerformed(evt);
            }
        });
        jPanel3.add(txttotaladd, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 30, 310, 30));

        jLabel43.setFont(new java.awt.Font("Trebuchet MS", 2, 22)); // NOI18N
        jLabel43.setText("Net Salary              :");
        jPanel3.add(jLabel43, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 80, 230, -1));

        txtnetsal.setEditable(false);
        txtnetsal.setBackground(new java.awt.Color(255, 255, 255));
        txtnetsal.setFont(new java.awt.Font("Trebuchet MS", 2, 22)); // NOI18N
        txtnetsal.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        txtnetsal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtnetsalActionPerformed(evt);
            }
        });
        jPanel3.add(txtnetsal, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 80, 310, 30));

        txtgross.setEditable(false);
        txtgross.setBackground(new java.awt.Color(255, 255, 255));
        txtgross.setFont(new java.awt.Font("Trebuchet MS", 2, 22)); // NOI18N
        txtgross.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        txtgross.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtgrossActionPerformed(evt);
            }
        });
        jPanel3.add(txtgross, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 80, 310, 30));

        jPanel2.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 530, 1160, 120));

        txtjoin.setBackground(new java.awt.Color(255, 255, 255));
        txtjoin.setForeground(new java.awt.Color(255, 0, 51));
        txtjoin.setDateFormatString("dd MMM,yyy");
        txtjoin.setEnabled(false);
        txtjoin.setFont(new java.awt.Font("Tahoma", 0, 19)); // NOI18N
        jPanel2.add(txtjoin, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 190, 280, 30));

        btnclear.setBackground(new java.awt.Color(255, 102, 0));
        btnclear.setFont(new java.awt.Font("Tahoma", 3, 20)); // NOI18N
        btnclear.setForeground(new java.awt.Color(255, 255, 255));
        btnclear.setText("CLEAR");
        btnclear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnclearActionPerformed(evt);
            }
        });
        jPanel2.add(btnclear, new org.netbeans.lib.awtextra.AbsoluteConstraints(1020, 500, 150, 30));

        pic.setText("Passport size photo");
        pic.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        jPanel2.add(pic, new org.netbeans.lib.awtextra.AbsoluteConstraints(1130, 40, 130, 130));

        btngenerate.setBackground(new java.awt.Color(255, 102, 0));
        btngenerate.setFont(new java.awt.Font("Tahoma", 3, 20)); // NOI18N
        btngenerate.setForeground(new java.awt.Color(255, 255, 255));
        btngenerate.setText("Generate Invoice");
        btngenerate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btngenerateActionPerformed(evt);
            }
        });
        jPanel2.add(btngenerate, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 500, 250, 30));

        btnquit.setBackground(new java.awt.Color(255, 102, 0));
        btnquit.setFont(new java.awt.Font("Tahoma", 3, 20)); // NOI18N
        btnquit.setForeground(new java.awt.Color(255, 255, 255));
        btnquit.setText("QUIT");
        btnquit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnquitActionPerformed(evt);
            }
        });
        jPanel2.add(btnquit, new org.netbeans.lib.awtextra.AbsoluteConstraints(1130, 370, 140, 30));

        btnback.setBackground(new java.awt.Color(255, 102, 0));
        btnback.setFont(new java.awt.Font("Tahoma", 3, 20)); // NOI18N
        btnback.setForeground(new java.awt.Color(255, 255, 255));
        btnback.setText("BACK");
        btnback.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnbackActionPerformed(evt);
            }
        });
        jPanel2.add(btnback, new org.netbeans.lib.awtextra.AbsoluteConstraints(1130, 310, 140, 30));

        scbar.setViewportView(jPanel2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(scbar, javax.swing.GroupLayout.DEFAULT_SIZE, 1198, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(scbar, javax.swing.GroupLayout.DEFAULT_SIZE, 658, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnquitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnquitActionPerformed
int ans;
        ans=JOptionPane.showConfirmDialog(null, "Are u sure ?","Quitting!",JOptionPane.YES_NO_OPTION,JOptionPane.QUESTION_MESSAGE);
        if(ans==JOptionPane.YES_OPTION)
        {
            dbutil.closeConnection();
            System.exit(0);
     
        }        // TODO add your handling code here:
   

        // TODO add your handling code here:
    }//GEN-LAST:event_btnquitActionPerformed

    private void btnbackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnbackActionPerformed
         this.dispose();
            AdminOptionFrame ad = new AdminOptionFrame();
            ad.setVisible(true);
     
               // TODO add your handling code here:
   



        // TODO add your handling code here:
    }//GEN-LAST:event_btnbackActionPerformed

    private void btnclearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnclearActionPerformed
this.dispose();
new GenerateInvoice().setVisible(true);


        // TODO add your handling code here:
    }//GEN-LAST:event_btnclearActionPerformed

    private void txtdesiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtdesiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtdesiActionPerformed

    private void btngenerateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btngenerateActionPerformed
invoice obj = new invoice();
JComboBox jc = (JComboBox)jmnth.getComboBox();
String sal_mnth = jc.getSelectedItem() +",";
sal_mnth = sal_mnth + jyr.getYear();



        obj.setSal_mm_yy(sal_mnth);
        obj.setDays((int)jsdays.getValue());
        obj.setLeaves((int)jsleave.getValue());
        obj.setPf((int)jspf.getValue());
        obj.setProfession_tax((int)jspro.getValue());
        
        obj.setAdvance((int)jsadv.getValue());
        obj.setBonus((int)jsbonus.getValue());
        obj.setInsurance((int)jsinsu.getValue());
        obj.setSpecial_allowance((int)jsallow.getValue());
        
        obj.setIncentive((int)jsinc.getValue());
        obj.setHra((int)jshra.getValue());
        obj.setConveyance_fixed((int)jsconf.getValue());
        obj.setConveyance_variable((int)jsconv.getValue());
        obj.setEmpid(jcempid.getSelectedItem().toString());
        
          obj.setEmpname(txtname.getText());
          obj.setDepartment(txtdep.getText());
          obj.setDesignation(txtdesi.getText());
          
          java.sql.Date d = new java.sql.Date(txtjoin.getDate().getTime());
          obj.setDate_of_join(d.toString());
          
          obj.setBasics(Integer.parseInt(txtbasics.getText()));
        
         obj.setTotal_add(total);
         obj.setTotal_ded(ded);
         obj.setGross_sal(net);
         obj.setNet_sal(total);
         obj.setPhoto(emp.getPho());
         
      new SlipFrame(obj).setVisible(true);


        // TODO add your handling code here:
    }//GEN-LAST:event_btngenerateActionPerformed

    private void txtdepActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtdepActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtdepActionPerformed

    private void txttotaladdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txttotaladdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txttotaladdActionPerformed

    private void txtnetsalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtnetsalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtnetsalActionPerformed

    private void txtgrossActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtgrossActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtgrossActionPerformed

    private void jPanel2MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel2MouseMoved
float sal1 = (emp.getSALARY() *1.0f)/30;
int sal = Math.round(sal1);
        ded = (sal*(int)jsleave.getValue())+(int)jspf.getValue() +(int)jspro.getValue() +(int)jsadv.getValue() +(int)jsinsu.getValue();
 txtbasics.setText(Math.round(sal1*(int)jsdays.getValue())+"");
total = (Math.round(sal1*(int)jsdays.getValue())) +(int)jsconv.getValue()
          +(int)jsconf.getValue()
          +(int)jsallow.getValue()+(int)jsinc.getValue()
          +(int)jshra.getValue()+(int)jsbonus.getValue() ;
net = total +ded ;

txttotaladd.setText(total+"");
txttotalded.setText(ded+"");
txtgross.setText(net+"");
txtnetsal.setText(total+"");

        // TODO add your handling code here:
    }//GEN-LAST:event_jPanel2MouseMoved

    private void jcempidActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcempidActionPerformed
String id = jcempid.getSelectedItem().toString();
try{
emp = Employees_jobDao.getEmpdetails(id);
txtname.setText(emp.getEMPNAME());
txtdesi.setText(emp.getDESIGNATION());
txtdep.setText(emp.getDEPARTMENT());
txtbasics.setText(emp.getSALARY()+"");
txtjoin.setDate(emp.getDATE_OF_JOINING());
Image img = emp.getImg().getScaledInstance(pic.getWidth(),pic.getHeight(),Image.SCALE_SMOOTH);
ImageIcon icon=new ImageIcon(img);
SlipFrame.ic = emp.getImg();
pic.setIcon(icon);
}
catch(Throwable th)
{
    th.printStackTrace();
}




        // TODO add your handling code here:
    }//GEN-LAST:event_jcempidActionPerformed

    private void jsdaysStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jsdaysStateChanged
int days , leaves ;
days = (int)jsdays.getValue();
leaves = (int)jsleave.getValue();
if(!(days+leaves ==30))
{
    leaves = 30 -days;
    jsleave.setValue(leaves);
}


        // TODO add your handling code here:
    }//GEN-LAST:event_jsdaysStateChanged

    private void jsleaveStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jsleaveStateChanged
int days , leaves ;
days = (int)jsdays.getValue();
leaves = (int)jsleave.getValue();
if(!(days+leaves ==30))
{
    days = 30 -leaves;
    jsdays.setValue(days);
}      
        

// TODO add your handling code here:
    }//GEN-LAST:event_jsleaveStateChanged

    private void jsconfStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jsconfStateChanged
      float sal1 = (emp.getSALARY() *1.0f)/30;
int sal = Math.round(sal1);
        ded = (sal*(int)jsleave.getValue())+(int)jspf.getValue() +(int)jspro.getValue() +(int)jsadv.getValue() +(int)jsinsu.getValue();
 txtbasics.setText(Math.round(sal1*(int)jsdays.getValue())+"");
total = (Math.round(sal1*(int)jsdays.getValue())) +(int)jsconv.getValue()
          +(int)jsconf.getValue()
          +(int)jsallow.getValue()+(int)jsinc.getValue()
          +(int)jshra.getValue()+(int)jsbonus.getValue() ;
net = total +ded ;

txttotaladd.setText(total+"");
txttotalded.setText(ded+"");
txtgross.setText(net+"");
txtnetsal.setText(total+"");
        

// TODO add your handling code here:
    }//GEN-LAST:event_jsconfStateChanged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GenerateInvoice.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GenerateInvoice.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GenerateInvoice.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GenerateInvoice.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GenerateInvoice().setVisible(true);
            }
        });
       

        
    }

    @Override
    public int getDefaultCloseOperation() {
        dbutil.closeConnection();
        return super.getDefaultCloseOperation(); //To change body of generated methods, choose Tools | Templates.
    }

   
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnback;
    private javax.swing.JButton btnclear;
    private javax.swing.JButton btngenerate;
    private javax.swing.JButton btnquit;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel42;
    private javax.swing.JLabel jLabel43;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JComboBox<String> jcempid;
    private com.toedter.calendar.JMonthChooser jmnth;
    private javax.swing.JSpinner jsadv;
    private javax.swing.JSpinner jsallow;
    private javax.swing.JSpinner jsbonus;
    private javax.swing.JSpinner jsconf;
    private javax.swing.JSpinner jsconv;
    private javax.swing.JSpinner jsdays;
    private javax.swing.JSpinner jshra;
    private javax.swing.JSpinner jsinc;
    private javax.swing.JSpinner jsinsu;
    private javax.swing.JSpinner jsleave;
    private javax.swing.JSpinner jspf;
    private javax.swing.JSpinner jspro;
    private com.toedter.calendar.JYearChooser jyr;
    private javax.swing.JLabel pic;
    private javax.swing.JScrollPane scbar;
    private javax.swing.JTextField txtbasics;
    private javax.swing.JTextField txtdep;
    private javax.swing.JTextField txtdesi;
    private javax.swing.JTextField txtgross;
    private com.toedter.calendar.JDateChooser txtjoin;
    private javax.swing.JTextField txtname;
    private javax.swing.JTextField txtnetsal;
    private javax.swing.JTextField txttotaladd;
    private javax.swing.JTextField txttotalded;
    // End of variables declaration//GEN-END:variables
 

}


