/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package khanaBadosh.Gui;

import java.awt.Dimension;
import java.awt.Image;
import java.awt.Toolkit;
import java.sql.SQLException;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.SwingUtilities;
import javax.swing.UIManager;
import khanaBadosh.Dao.loginDao;
import khanaBadosh.dbutil.dbutil;
import khanaBadosh.pojo.UserProfile;
import khanaBadosh.pojo.login;

/**
 *
 * @author HP
 */
public class LoginFrame extends javax.swing.JFrame {

    private String userid;
    private String password;

    /**
     * Creates new form LoginFrame
     */
    public LoginFrame() {
        initComponents();
        this.setLocationRelativeTo(null);
         try {
             Dimension d = Toolkit.getDefaultToolkit().getScreenSize();
         setBounds(0,0,d.width, d.height);
         jPanel1.setBounds(0, 0, d.width, d.height);
     UIManager.setLookAndFeel("com.sun.java.swing.plaf.windows.WindowsLookAndFeel");
   SwingUtilities.updateComponentTreeUI(scbar);
  
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
             SwingUtilities.updateComponentTreeUI(jPanel1);
        } catch (Throwable ex) {
            java.util.logging.Logger.getLogger(ViewFuelFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        this.setLocationRelativeTo(null);
        Toolkit t = Toolkit.getDefaultToolkit();
        Image im = t.getImage(getClass().getResource("/IMAGES/title.jpg"));
        setIconImage(im);
  Image img = t.getImage(getClass().getResource("/IMAGES/SIDE3.jpg")).getScaledInstance(jLabel5.getWidth(),jLabel5.getHeight(),Image.SCALE_SMOOTH);
ImageIcon icon=new ImageIcon(img);
jLabel5.setIcon(icon);
 img = t.getImage(getClass().getResource("/IMAGES/SIDE.jpg")).getScaledInstance(jLabel6.getWidth(),jLabel6.getHeight(),Image.SCALE_SMOOTH);
 icon=new ImageIcon(img);
jLabel6.setIcon(icon);
 img = t.getImage(getClass().getResource("/IMAGES/Untitled-1-copy.jpg")).getScaledInstance(jLabel8.getWidth(),jLabel8.getHeight(),Image.SCALE_SMOOTH);
 icon=new ImageIcon(img);
jLabel8.setIcon(icon);


    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        scbar = new javax.swing.JScrollPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        btnlogin = new javax.swing.JButton();
        btnquit = new javax.swing.JButton();
        txtuserid = new javax.swing.JTextField();
        txtpassword = new javax.swing.JPasswordField();
        jPanel3 = new javax.swing.JPanel();
        btnadmin = new javax.swing.JRadioButton();
        btncashier = new javax.swing.JRadioButton();
        jLabel9 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("KHANABADOSH EMPLOYEES MANAGEMENT");
        setPreferredSize(new java.awt.Dimension(1360, 760));
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGES/login-gif-13.gif"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(-20, 0, 330, 420));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "LOGIN DETAILS\n", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.ABOVE_TOP, new java.awt.Font("Tahoma", 1, 22), new java.awt.Color(255, 102, 0))); // NOI18N
        jPanel2.setForeground(new java.awt.Color(0, 153, 153));
        jPanel2.setMinimumSize(new java.awt.Dimension(200, 150));
        jPanel2.setPreferredSize(new java.awt.Dimension(200, 150));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 14, 19));
        jLabel2.setText("USERID         :");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, 190, 30));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 14, 19));
        jLabel3.setText("PASSWORD   :");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 130, 190, 30));

        btnlogin.setBackground(new java.awt.Color(255, 0, 0));
        btnlogin.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnlogin.setForeground(new java.awt.Color(255, 255, 255));
        btnlogin.setText("LOGIN");
        btnlogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnloginActionPerformed(evt);
            }
        });
        jPanel2.add(btnlogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 190, 140, 30));

        btnquit.setBackground(new java.awt.Color(255, 0, 0));
        btnquit.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnquit.setForeground(new java.awt.Color(255, 255, 255));
        btnquit.setText("QUIT");
        btnquit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnquitActionPerformed(evt);
            }
        });
        jPanel2.add(btnquit, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 190, 130, 30));

        txtuserid.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        jPanel2.add(txtuserid, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 70, 319, -1));

        txtpassword.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        txtpassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtpasswordActionPerformed(evt);
            }
        });
        jPanel2.add(txtpassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 140, 319, -1));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 180, 590, 230));

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "USER TYPE\n\n", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.ABOVE_TOP, new java.awt.Font("Tahoma", 1, 22), new java.awt.Color(255, 102, 0))); // NOI18N
        jPanel3.setForeground(new java.awt.Color(0, 102, 102));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnadmin.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroup1.add(btnadmin);
        btnadmin.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        btnadmin.setForeground(new java.awt.Color(255, 14, 19));
        btnadmin.setText("ADMIN");
        jPanel3.add(btnadmin, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, -1, -1));

        btncashier.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroup1.add(btncashier);
        btncashier.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        btncashier.setForeground(new java.awt.Color(255, 14, 19));
        btncashier.setText("MASTER ADMIN");
        jPanel3.add(btncashier, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 50, -1, -1));

        jLabel9.setText("Get IP");
        jLabel9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel9MouseClicked(evt);
            }
        });
        jPanel3.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 6, 60, 20));

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 420, 590, 110));

        jLabel4.setBackground(new java.awt.Color(255, 102, 0));
        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 51, 0));
        jLabel4.setText("USER LOGIN DETAILS");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 140, 350, -1));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGES/SIDE.jpg"))); // NOI18N
        jLabel6.setText("jLabel5");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(940, 0, 260, 530));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGES/SIDE3.jpg"))); // NOI18N
        jLabel5.setText("jLabel5");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 360, 260, 310));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGES/SIDE2.jpg"))); // NOI18N
        jLabel7.setText("jLabel7");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 530, 970, 140));

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGES/Untitled-1-copy.jpg"))); // NOI18N
        jLabel8.setText("jLabel8");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 0, 720, 130));

        scbar.setViewportView(jPanel1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(scbar, javax.swing.GroupLayout.DEFAULT_SIZE, 1198, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(scbar, javax.swing.GroupLayout.DEFAULT_SIZE, 671, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtpasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtpasswordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtpasswordActionPerformed

    private void btnquitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnquitActionPerformed
        int ans;
        ans = JOptionPane.showConfirmDialog(null, "Are u sure ?", "Quitting!", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);
        if (ans == JOptionPane.YES_OPTION) {
             System.exit(0);
            dbutil.closeConnection();
           
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_btnquitActionPerformed

    private void btnloginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnloginActionPerformed
        if (validateInput()) {
            String userType = getUserType();
            if (userType == null) {
                JOptionPane.showMessageDialog(null, "Please Select the User Type", "ERROR!", JOptionPane.ERROR_MESSAGE);
                return;
            }
            try {
                login user = new login();
                user.setUserId(userid);
                user.setPassword(password);
                user.setUserType(userType);
                String username = loginDao.validateUser(user);
                if (username != null) {
                    JOptionPane.showMessageDialog(null, "Login Accepted!", "Welcome " + username, JOptionPane.INFORMATION_MESSAGE);
                    UserProfile.setUsername(username);
                    UserProfile.setUsertype(userType);

                  AdminOptionFrame adminFrame = new AdminOptionFrame();
                        adminFrame.setVisible(true);
                    
                    this.dispose();

                } else {
                    JOptionPane.showMessageDialog(null, "Invalid UserId/Password", "Login Denied!", JOptionPane.ERROR_MESSAGE);
                }

            } catch (SQLException ex) {
                JOptionPane.showMessageDialog(null, "ERROR IN SQL PART" + ex, "ERROR in DB!", JOptionPane.ERROR_MESSAGE);

                ex.printStackTrace();
            }
        } else {
            JOptionPane.showMessageDialog(null, "Please Fill the Userid/Password", "EMPTY userid/Password!", JOptionPane.ERROR_MESSAGE);
            return;
        }

        // TODO add your handling code here:
    }//GEN-LAST:event_btnloginActionPerformed

    private void jLabel9MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel9MouseClicked
try{
        JOptionPane.showMessageDialog(null,"Enter this ID :\n"+ testing.add(),"ID",JOptionPane.INFORMATION_MESSAGE);
       
}
catch(Throwable th)
{
    th.printStackTrace();
}



        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel9MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LoginFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LoginFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LoginFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LoginFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LoginFrame().setVisible(true);
            }
        });
    }

    public boolean validateInput() {
        userid = txtuserid.getText();
        char[] pwd = txtpassword.getPassword();
        password = String.valueOf(pwd);
        System.out.println(password);
        if (userid.isEmpty() || password.length() == 0) {
            return false;
        } else {
            return true;
        }
    }

    private String getUserType() {
        if (btnadmin.isSelected()) {
            return btnadmin.getText();
        } else if (btncashier.isSelected()) {
            return btncashier.getText();
        } else {
            return null;
        }
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton btnadmin;
    private javax.swing.JRadioButton btncashier;
    private javax.swing.JButton btnlogin;
    private javax.swing.JButton btnquit;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane scbar;
    private javax.swing.JPasswordField txtpassword;
    private javax.swing.JTextField txtuserid;
    // End of variables declaration//GEN-END:variables
}
